async function processLanguageAlphabets(languageCode: string, alphabets: string[]) {
  const language = await this.getLanguagesByCode(languageCode)

  await Promise.all(
    alphabets.map(async (alphabet) => {
      await this.entityManager.save('language_alphabets', {
        language,
        alphabet,
      })
    }),
  )
}

export default async function () {
  return new Promise(async (resolve, reject) => {
    try {
      await this.entityManager.upsert(
        'languages',
        [
          {
            name: 'English',
            code: 'en-US',
          },
          {
            name: 'Japanese',
            code: 'ja-JP',
          },
          {
            name: 'Japanese Kana',
            code: 'ja-Kana',
          },
          {
            name: 'Spanish',
            code: 'es-ES',
          },
          {
            name: 'Chinese',
            code: 'zh-CN',
          },
          {
            name: 'German',
            code: 'de-DE',
          },
          {
            name: 'Hindi',
            code: 'hi-IN',
          },
          {
            name: 'French',
            code: 'fr-FR',
          },
          {
            name: 'Italian',
            code: 'it-IT',
          },
        ],
        ['name'],
      )

      await this.entityManager.delete('language_alphabets', {})

      await processLanguageAlphabets.bind(this)('en-US', [
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
      ])

      await processLanguageAlphabets.bind(this)('ja-JP', [
        'ア',
        'イ',
        'ウ',
        'エ',
        'オ',
        'カ',
        'キ',
        'ク',
        'ケ',
        'コ',
        'サ',
        'シ',
        'ス',
        'セ',
        'ソ',
        'タ',
        'チ',
        'ツ',
        'テ',
        'ト',
        'ナ',
        'ニ',
        'ヌ',
        'ネ',
        'ノ',
        'ハ',
        'ヒ',
        'フ',
        'ヘ',
        'ホ',
        'マ',
        'ミ',
        'ム',
        'メ',
        'モ',
        'ヤ',
        'ユ',
        'ヨ',
        'ラ',
        'リ',
        'ル',
        'レ',
        'ロ',
        'ワ',
        'ヲ',
        'ン',
      ])

      await processLanguageAlphabets.bind(this)('ja-Kana', [
        'ア',
        'イ',
        'ウ',
        'エ',
        'オ',
        'カ',
        'キ',
        'ク',
        'ケ',
        'コ',
        'サ',
        'シ',
        'ス',
        'セ',
        'ソ',
        'タ',
        'チ',
        'ツ',
        'テ',
        'ト',
        'ナ',
        'ニ',
        'ヌ',
        'ネ',
        'ノ',
        'ハ',
        'ヒ',
        'フ',
        'ヘ',
        'ホ',
        'マ',
        'ミ',
        'ム',
        'メ',
        'モ',
        'ヤ',
        'ユ',
        'ヨ',
        'ラ',
        'リ',
        'ル',
        'レ',
        'ロ',
        'ワ',
        'ヲ',
        'ン',
      ])

      await processLanguageAlphabets.bind(this)('es-ES', [
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'Ñ',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
      ])

      await processLanguageAlphabets.bind(this)('zh-CN', [
        '字',
        '一',
        '二',
        '三',
        '四',
        '五',
        '六',
        '七',
        '八',
        '九',
        '十',
        '百',
        '千',
        '万',
        '亿',
      ])

      await processLanguageAlphabets.bind(this)('de-DE', [
        'A',
        'Ä',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'Ö',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'Ü',
        'V',
        'W',
        'X',
        'Y',
        'Z',
      ])

      await processLanguageAlphabets.bind(this)('hi-IN', [
        'अ',
        'आ',
        'इ',
        'ई',
        'उ',
        'ऊ',
        'ऋ',
        'ए',
        'ऐ',
        'ओ',
        'औ',
        'क',
        'ख',
        'ग',
        'घ',
        'च',
        'छ',
        'ज',
        'झ',
        'ट',
        'ठ',
        'ड',
        'ढ',
        'ण',
        'त',
        'थ',
        'द',
        'ध',
        'न',
        'प',
        'फ',
        'ब',
        'भ',
        'म',
        'य',
        'र',
        'ल',
        'व',
        'श',
        'ष',
        'स',
        'ह',
      ])

      await processLanguageAlphabets.bind(this)('fr-FR', [
        'A',
        'À',
        'Â',
        'Ä',
        'Æ',
        'B',
        'C',
        'Ç',
        'D',
        'E',
        'É',
        'È',
        'Ê',
        'Ë',
        'F',
        'G',
        'H',
        'I',
        'Î',
        'Ï',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'Ô',
        'Œ',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'Ù',
        'Û',
        'Ü',
        'V',
        'W',
        'X',
        'Y',
        'Ÿ',
        'Z',
      ])

      await processLanguageAlphabets.bind(this)('it-IT', [
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'Z',
      ])

      resolve('success')
    } catch (error) {
      reject(error)
    }
  })
}
