export enum HomepageTitle {
  TRENDING_DEALS = 'TRENDING_DEALS',
  POPULAR_CATEGORY = 'POPULAR_CATEGORY',
  POPULAR_BRAND = 'POPULAR_BRAND',
  VIEW_HISTORY = 'VIEW_HISTORY',
  INFLUENCER_RANKING = 'INFLUENCER_RANKING',
  BUSINESS_RANKING = 'BUSINESS_RANKING',
  EDITOR_PICKS = 'EDITOR_PICKS',
  CATEGORY_LIST = 'CATEGORY_LIST',
  BRAND_LIST = 'BRAND_LIST',
  USER_LIST = 'USER_LIST',
  CUSTOM_LIST = 'CUSTOM_LIST',
}
