export default {
  'Africa/Abidjan': {
    abbr: 'GMT',
    raw_offset: 0,
    timezone: 'Africa/Abidjan',
    utc_offset: '+00:00',
  },
  'Africa/Algiers': {
    abbr: 'CET',
    raw_offset: 3600,
    timezone: 'Africa/Algiers',
    utc_offset: '+01:00',
  },
  'Africa/Bissau': {
    abbr: 'GMT',
    raw_offset: 0,
    timezone: 'Africa/Bissau',
    utc_offset: '+00:00',
  },
  'Africa/Cairo': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Africa/Cairo',
    utc_offset: '+03:00',
  },
  'Africa/Casablanca': {
    abbr: '+01',
    raw_offset: 3600,
    timezone: 'Africa/Casablanca',
    utc_offset: '+01:00',
  },
  'Africa/Ceuta': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Africa/Ceuta',
    utc_offset: '+02:00',
  },
  'Africa/El_Aaiun': {
    abbr: '+01',
    raw_offset: 3600,
    timezone: 'Africa/El_Aaiun',
    utc_offset: '+01:00',
  },
  'Africa/Johannesburg': {
    abbr: 'SAST',
    raw_offset: 7200,
    timezone: 'Africa/Johannesburg',
    utc_offset: '+02:00',
  },
  'Africa/Juba': {
    abbr: 'CAT',
    raw_offset: 7200,
    timezone: 'Africa/Juba',
    utc_offset: '+02:00',
  },
  'Africa/Khartoum': {
    abbr: 'CAT',
    raw_offset: 7200,
    timezone: 'Africa/Khartoum',
    utc_offset: '+02:00',
  },
  'Africa/Lagos': {
    abbr: 'WAT',
    raw_offset: 3600,
    timezone: 'Africa/Lagos',
    utc_offset: '+01:00',
  },
  'Africa/Maputo': {
    abbr: 'CAT',
    raw_offset: 7200,
    timezone: 'Africa/Maputo',
    utc_offset: '+02:00',
  },
  'Africa/Monrovia': {
    abbr: 'GMT',
    raw_offset: 0,
    timezone: 'Africa/Monrovia',
    utc_offset: '+00:00',
  },
  'Africa/Nairobi': {
    abbr: 'EAT',
    raw_offset: 10800,
    timezone: 'Africa/Nairobi',
    utc_offset: '+03:00',
  },
  'Africa/Ndjamena': {
    abbr: 'WAT',
    raw_offset: 3600,
    timezone: 'Africa/Ndjamena',
    utc_offset: '+01:00',
  },
  'Africa/Sao_Tome': {
    abbr: 'GMT',
    raw_offset: 0,
    timezone: 'Africa/Sao_Tome',
    utc_offset: '+00:00',
  },
  'Africa/Tripoli': {
    abbr: 'EET',
    raw_offset: 7200,
    timezone: 'Africa/Tripoli',
    utc_offset: '+02:00',
  },
  'Africa/Tunis': {
    abbr: 'CET',
    raw_offset: 3600,
    timezone: 'Africa/Tunis',
    utc_offset: '+01:00',
  },
  'Africa/Windhoek': {
    abbr: 'CAT',
    raw_offset: 7200,
    timezone: 'Africa/Windhoek',
    utc_offset: '+02:00',
  },
  'America/Adak': {
    abbr: 'HDT',
    raw_offset: -36000,
    timezone: 'America/Adak',
    utc_offset: '-09:00',
  },
  'America/Anchorage': {
    abbr: 'AKDT',
    raw_offset: -32400,
    timezone: 'America/Anchorage',
    utc_offset: '-08:00',
  },
  'America/Araguaina': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Araguaina',
    utc_offset: '-03:00',
  },
  'America/Argentina/Buenos_Aires': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/Buenos_Aires',
    utc_offset: '-03:00',
  },
  'America/Argentina/Catamarca': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/Catamarca',
    utc_offset: '-03:00',
  },
  'America/Argentina/Cordoba': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/Cordoba',
    utc_offset: '-03:00',
  },
  'America/Argentina/Jujuy': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/Jujuy',
    utc_offset: '-03:00',
  },
  'America/Argentina/La_Rioja': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/La_Rioja',
    utc_offset: '-03:00',
  },
  'America/Argentina/Mendoza': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/Mendoza',
    utc_offset: '-03:00',
  },
  'America/Argentina/Rio_Gallegos': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/Rio_Gallegos',
    utc_offset: '-03:00',
  },
  'America/Argentina/Salta': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/Salta',
    utc_offset: '-03:00',
  },
  'America/Argentina/San_Juan': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/San_Juan',
    utc_offset: '-03:00',
  },
  'America/Argentina/San_Luis': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/San_Luis',
    utc_offset: '-03:00',
  },
  'America/Argentina/Tucuman': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/Tucuman',
    utc_offset: '-03:00',
  },
  'America/Argentina/Ushuaia': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Argentina/Ushuaia',
    utc_offset: '-03:00',
  },
  'America/Asuncion': {
    abbr: '-04',
    raw_offset: -14400,
    timezone: 'America/Asuncion',
    utc_offset: '-04:00',
  },
  'America/Bahia': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Bahia',
    utc_offset: '-03:00',
  },
  'America/Bahia_Banderas': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Bahia_Banderas',
    utc_offset: '-06:00',
  },
  'America/Barbados': {
    abbr: 'AST',
    raw_offset: -14400,
    timezone: 'America/Barbados',
    utc_offset: '-04:00',
  },
  'America/Belem': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Belem',
    utc_offset: '-03:00',
  },
  'America/Belize': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Belize',
    utc_offset: '-06:00',
  },
  'America/Boa_Vista': {
    abbr: '-04',
    raw_offset: -14400,
    timezone: 'America/Boa_Vista',
    utc_offset: '-04:00',
  },
  'America/Bogota': {
    abbr: '-05',
    raw_offset: -18000,
    timezone: 'America/Bogota',
    utc_offset: '-05:00',
  },
  'America/Boise': {
    abbr: 'MDT',
    raw_offset: -25200,
    timezone: 'America/Boise',
    utc_offset: '-06:00',
  },
  'America/Cambridge_Bay': {
    abbr: 'MDT',
    raw_offset: -25200,
    timezone: 'America/Cambridge_Bay',
    utc_offset: '-06:00',
  },
  'America/Campo_Grande': {
    abbr: '-04',
    raw_offset: -14400,
    timezone: 'America/Campo_Grande',
    utc_offset: '-04:00',
  },
  'America/Cancun': {
    abbr: 'EST',
    raw_offset: -18000,
    timezone: 'America/Cancun',
    utc_offset: '-05:00',
  },
  'America/Caracas': {
    abbr: '-04',
    raw_offset: -14400,
    timezone: 'America/Caracas',
    utc_offset: '-04:00',
  },
  'America/Cayenne': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Cayenne',
    utc_offset: '-03:00',
  },
  'America/Chicago': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/Chicago',
    utc_offset: '-05:00',
  },
  'America/Chihuahua': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Chihuahua',
    utc_offset: '-06:00',
  },
  'America/Ciudad_Juarez': {
    abbr: 'MDT',
    raw_offset: -25200,
    timezone: 'America/Ciudad_Juarez',
    utc_offset: '-06:00',
  },
  'America/Costa_Rica': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Costa_Rica',
    utc_offset: '-06:00',
  },
  'America/Cuiaba': {
    abbr: '-04',
    raw_offset: -14400,
    timezone: 'America/Cuiaba',
    utc_offset: '-04:00',
  },
  'America/Danmarkshavn': {
    abbr: 'GMT',
    raw_offset: 0,
    timezone: 'America/Danmarkshavn',
    utc_offset: '+00:00',
  },
  'America/Dawson': {
    abbr: 'MST',
    raw_offset: -25200,
    timezone: 'America/Dawson',
    utc_offset: '-07:00',
  },
  'America/Dawson_Creek': {
    abbr: 'MST',
    raw_offset: -25200,
    timezone: 'America/Dawson_Creek',
    utc_offset: '-07:00',
  },
  'America/Denver': {
    abbr: 'MDT',
    raw_offset: -25200,
    timezone: 'America/Denver',
    utc_offset: '-06:00',
  },
  'America/Detroit': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Detroit',
    utc_offset: '-04:00',
  },
  'America/Edmonton': {
    abbr: 'MDT',
    raw_offset: -25200,
    timezone: 'America/Edmonton',
    utc_offset: '-06:00',
  },
  'America/Eirunepe': {
    abbr: '-05',
    raw_offset: -18000,
    timezone: 'America/Eirunepe',
    utc_offset: '-05:00',
  },
  'America/El_Salvador': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/El_Salvador',
    utc_offset: '-06:00',
  },
  'America/Fort_Nelson': {
    abbr: 'MST',
    raw_offset: -25200,
    timezone: 'America/Fort_Nelson',
    utc_offset: '-07:00',
  },
  'America/Fortaleza': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Fortaleza',
    utc_offset: '-03:00',
  },
  'America/Glace_Bay': {
    abbr: 'ADT',
    raw_offset: -14400,
    timezone: 'America/Glace_Bay',
    utc_offset: '-03:00',
  },
  'America/Goose_Bay': {
    abbr: 'ADT',
    raw_offset: -14400,
    timezone: 'America/Goose_Bay',
    utc_offset: '-03:00',
  },
  'America/Grand_Turk': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Grand_Turk',
    utc_offset: '-04:00',
  },
  'America/Guatemala': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Guatemala',
    utc_offset: '-06:00',
  },
  'America/Guayaquil': {
    abbr: '-05',
    raw_offset: -18000,
    timezone: 'America/Guayaquil',
    utc_offset: '-05:00',
  },
  'America/Guyana': {
    abbr: '-04',
    raw_offset: -14400,
    timezone: 'America/Guyana',
    utc_offset: '-04:00',
  },
  'America/Halifax': {
    abbr: 'ADT',
    raw_offset: -14400,
    timezone: 'America/Halifax',
    utc_offset: '-03:00',
  },
  'America/Havana': {
    abbr: 'CDT',
    raw_offset: -18000,
    timezone: 'America/Havana',
    utc_offset: '-04:00',
  },
  'America/Hermosillo': {
    abbr: 'MST',
    raw_offset: -25200,
    timezone: 'America/Hermosillo',
    utc_offset: '-07:00',
  },
  'America/Indiana/Indianapolis': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Indiana/Indianapolis',
    utc_offset: '-04:00',
  },
  'America/Indiana/Knox': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/Indiana/Knox',
    utc_offset: '-05:00',
  },
  'America/Indiana/Marengo': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Indiana/Marengo',
    utc_offset: '-04:00',
  },
  'America/Indiana/Petersburg': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Indiana/Petersburg',
    utc_offset: '-04:00',
  },
  'America/Indiana/Tell_City': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/Indiana/Tell_City',
    utc_offset: '-05:00',
  },
  'America/Indiana/Vevay': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Indiana/Vevay',
    utc_offset: '-04:00',
  },
  'America/Indiana/Vincennes': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Indiana/Vincennes',
    utc_offset: '-04:00',
  },
  'America/Indiana/Winamac': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Indiana/Winamac',
    utc_offset: '-04:00',
  },
  'America/Inuvik': {
    abbr: 'MDT',
    raw_offset: -25200,
    timezone: 'America/Inuvik',
    utc_offset: '-06:00',
  },
  'America/Iqaluit': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Iqaluit',
    utc_offset: '-04:00',
  },
  'America/Jamaica': {
    abbr: 'EST',
    raw_offset: -18000,
    timezone: 'America/Jamaica',
    utc_offset: '-05:00',
  },
  'America/Juneau': {
    abbr: 'AKDT',
    raw_offset: -32400,
    timezone: 'America/Juneau',
    utc_offset: '-08:00',
  },
  'America/Kentucky/Louisville': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Kentucky/Louisville',
    utc_offset: '-04:00',
  },
  'America/Kentucky/Monticello': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Kentucky/Monticello',
    utc_offset: '-04:00',
  },
  'America/La_Paz': {
    abbr: '-04',
    raw_offset: -14400,
    timezone: 'America/La_Paz',
    utc_offset: '-04:00',
  },
  'America/Lima': {
    abbr: '-05',
    raw_offset: -18000,
    timezone: 'America/Lima',
    utc_offset: '-05:00',
  },
  'America/Los_Angeles': {
    abbr: 'PDT',
    raw_offset: -28800,
    timezone: 'America/Los_Angeles',
    utc_offset: '-07:00',
  },
  'America/Maceio': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Maceio',
    utc_offset: '-03:00',
  },
  'America/Managua': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Managua',
    utc_offset: '-06:00',
  },
  'America/Manaus': {
    abbr: '-04',
    raw_offset: -14400,
    timezone: 'America/Manaus',
    utc_offset: '-04:00',
  },
  'America/Martinique': {
    abbr: 'AST',
    raw_offset: -14400,
    timezone: 'America/Martinique',
    utc_offset: '-04:00',
  },
  'America/Matamoros': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/Matamoros',
    utc_offset: '-05:00',
  },
  'America/Mazatlan': {
    abbr: 'MST',
    raw_offset: -25200,
    timezone: 'America/Mazatlan',
    utc_offset: '-07:00',
  },
  'America/Menominee': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/Menominee',
    utc_offset: '-05:00',
  },
  'America/Merida': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Merida',
    utc_offset: '-06:00',
  },
  'America/Metlakatla': {
    abbr: 'AKDT',
    raw_offset: -32400,
    timezone: 'America/Metlakatla',
    utc_offset: '-08:00',
  },
  'America/Mexico_City': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Mexico_City',
    utc_offset: '-06:00',
  },
  'America/Miquelon': {
    abbr: '-02',
    raw_offset: -10800,
    timezone: 'America/Miquelon',
    utc_offset: '-02:00',
  },
  'America/Moncton': {
    abbr: 'ADT',
    raw_offset: -14400,
    timezone: 'America/Moncton',
    utc_offset: '-03:00',
  },
  'America/Monterrey': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Monterrey',
    utc_offset: '-06:00',
  },
  'America/Montevideo': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Montevideo',
    utc_offset: '-03:00',
  },
  'America/New_York': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/New_York',
    utc_offset: '-04:00',
  },
  'America/Nome': {
    abbr: 'AKDT',
    raw_offset: -32400,
    timezone: 'America/Nome',
    utc_offset: '-08:00',
  },
  'America/Noronha': {
    abbr: '-02',
    raw_offset: -7200,
    timezone: 'America/Noronha',
    utc_offset: '-02:00',
  },
  'America/North_Dakota/Beulah': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/North_Dakota/Beulah',
    utc_offset: '-05:00',
  },
  'America/North_Dakota/Center': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/North_Dakota/Center',
    utc_offset: '-05:00',
  },
  'America/North_Dakota/New_Salem': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/North_Dakota/New_Salem',
    utc_offset: '-05:00',
  },
  'America/Nuuk': {
    abbr: '-02',
    raw_offset: -10800,
    timezone: 'America/Nuuk',
    utc_offset: '-02:00',
  },
  'America/Ojinaga': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/Ojinaga',
    utc_offset: '-05:00',
  },
  'America/Panama': {
    abbr: 'EST',
    raw_offset: -18000,
    timezone: 'America/Panama',
    utc_offset: '-05:00',
  },
  'America/Paramaribo': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Paramaribo',
    utc_offset: '-03:00',
  },
  'America/Phoenix': {
    abbr: 'MST',
    raw_offset: -25200,
    timezone: 'America/Phoenix',
    utc_offset: '-07:00',
  },
  'America/Port-au-Prince': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Port-au-Prince',
    utc_offset: '-04:00',
  },
  'America/Porto_Velho': {
    abbr: '-04',
    raw_offset: -14400,
    timezone: 'America/Porto_Velho',
    utc_offset: '-04:00',
  },
  'America/Puerto_Rico': {
    abbr: 'AST',
    raw_offset: -14400,
    timezone: 'America/Puerto_Rico',
    utc_offset: '-04:00',
  },
  'America/Punta_Arenas': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Punta_Arenas',
    utc_offset: '-03:00',
  },
  'America/Rankin_Inlet': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/Rankin_Inlet',
    utc_offset: '-05:00',
  },
  'America/Recife': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Recife',
    utc_offset: '-03:00',
  },
  'America/Regina': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Regina',
    utc_offset: '-06:00',
  },
  'America/Resolute': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/Resolute',
    utc_offset: '-05:00',
  },
  'America/Rio_Branco': {
    abbr: '-05',
    raw_offset: -18000,
    timezone: 'America/Rio_Branco',
    utc_offset: '-05:00',
  },
  'America/Santarem': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Santarem',
    utc_offset: '-03:00',
  },
  'America/Santiago': {
    abbr: '-04',
    raw_offset: -14400,
    timezone: 'America/Santiago',
    utc_offset: '-04:00',
  },
  'America/Santo_Domingo': {
    abbr: 'AST',
    raw_offset: -14400,
    timezone: 'America/Santo_Domingo',
    utc_offset: '-04:00',
  },
  'America/Sao_Paulo': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'America/Sao_Paulo',
    utc_offset: '-03:00',
  },
  'America/Scoresbysund': {
    abbr: '+00',
    raw_offset: -3600,
    timezone: 'America/Scoresbysund',
    utc_offset: '+00:00',
  },
  'America/Sitka': {
    abbr: 'AKDT',
    raw_offset: -32400,
    timezone: 'America/Sitka',
    utc_offset: '-08:00',
  },
  'America/St_Johns': {
    abbr: 'NDT',
    raw_offset: -12600,
    timezone: 'America/St_Johns',
    utc_offset: '-02:30',
  },
  'America/Swift_Current': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Swift_Current',
    utc_offset: '-06:00',
  },
  'America/Tegucigalpa': {
    abbr: 'CST',
    raw_offset: -21600,
    timezone: 'America/Tegucigalpa',
    utc_offset: '-06:00',
  },
  'America/Thule': {
    abbr: 'ADT',
    raw_offset: -14400,
    timezone: 'America/Thule',
    utc_offset: '-03:00',
  },
  'America/Tijuana': {
    abbr: 'PDT',
    raw_offset: -28800,
    timezone: 'America/Tijuana',
    utc_offset: '-07:00',
  },
  'America/Toronto': {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'America/Toronto',
    utc_offset: '-04:00',
  },
  'America/Vancouver': {
    abbr: 'PDT',
    raw_offset: -28800,
    timezone: 'America/Vancouver',
    utc_offset: '-07:00',
  },
  'America/Whitehorse': {
    abbr: 'MST',
    raw_offset: -25200,
    timezone: 'America/Whitehorse',
    utc_offset: '-07:00',
  },
  'America/Winnipeg': {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'America/Winnipeg',
    utc_offset: '-05:00',
  },
  'America/Yakutat': {
    abbr: 'AKDT',
    raw_offset: -32400,
    timezone: 'America/Yakutat',
    utc_offset: '-08:00',
  },
  'Antarctica/Casey': {
    abbr: '+11',
    raw_offset: 39600,
    timezone: 'Antarctica/Casey',
    utc_offset: '+11:00',
  },
  'Antarctica/Davis': {
    abbr: '+07',
    raw_offset: 25200,
    timezone: 'Antarctica/Davis',
    utc_offset: '+07:00',
  },
  'Antarctica/Macquarie': {
    abbr: 'AEST',
    raw_offset: 36000,
    timezone: 'Antarctica/Macquarie',
    utc_offset: '+10:00',
  },
  'Antarctica/Mawson': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Antarctica/Mawson',
    utc_offset: '+05:00',
  },
  'Antarctica/Palmer': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'Antarctica/Palmer',
    utc_offset: '-03:00',
  },
  'Antarctica/Rothera': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'Antarctica/Rothera',
    utc_offset: '-03:00',
  },
  'Antarctica/Troll': {
    abbr: '+02',
    raw_offset: 0,
    timezone: 'Antarctica/Troll',
    utc_offset: '+02:00',
  },
  'Asia/Almaty': {
    abbr: '+06',
    raw_offset: 21600,
    timezone: 'Asia/Almaty',
    utc_offset: '+06:00',
  },
  'Asia/Amman': {
    abbr: '+03',
    raw_offset: 10800,
    timezone: 'Asia/Amman',
    utc_offset: '+03:00',
  },
  'Asia/Anadyr': {
    abbr: '+12',
    raw_offset: 43200,
    timezone: 'Asia/Anadyr',
    utc_offset: '+12:00',
  },
  'Asia/Aqtau': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Asia/Aqtau',
    utc_offset: '+05:00',
  },
  'Asia/Aqtobe': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Asia/Aqtobe',
    utc_offset: '+05:00',
  },
  'Asia/Ashgabat': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Asia/Ashgabat',
    utc_offset: '+05:00',
  },
  'Asia/Atyrau': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Asia/Atyrau',
    utc_offset: '+05:00',
  },
  'Asia/Baghdad': {
    abbr: '+03',
    raw_offset: 10800,
    timezone: 'Asia/Baghdad',
    utc_offset: '+03:00',
  },
  'Asia/Baku': {
    abbr: '+04',
    raw_offset: 14400,
    timezone: 'Asia/Baku',
    utc_offset: '+04:00',
  },
  'Asia/Bangkok': {
    abbr: '+07',
    raw_offset: 25200,
    timezone: 'Asia/Bangkok',
    utc_offset: '+07:00',
  },
  'Asia/Barnaul': {
    abbr: '+07',
    raw_offset: 25200,
    timezone: 'Asia/Barnaul',
    utc_offset: '+07:00',
  },
  'Asia/Beirut': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Asia/Beirut',
    utc_offset: '+03:00',
  },
  'Asia/Bishkek': {
    abbr: '+06',
    raw_offset: 21600,
    timezone: 'Asia/Bishkek',
    utc_offset: '+06:00',
  },
  'Asia/Chita': {
    abbr: '+09',
    raw_offset: 32400,
    timezone: 'Asia/Chita',
    utc_offset: '+09:00',
  },
  'Asia/Choibalsan': {
    abbr: '+08',
    raw_offset: 28800,
    timezone: 'Asia/Choibalsan',
    utc_offset: '+08:00',
  },
  'Asia/Colombo': {
    abbr: '+0530',
    raw_offset: 19800,
    timezone: 'Asia/Colombo',
    utc_offset: '+05:30',
  },
  'Asia/Damascus': {
    abbr: '+03',
    raw_offset: 10800,
    timezone: 'Asia/Damascus',
    utc_offset: '+03:00',
  },
  'Asia/Dhaka': {
    abbr: '+06',
    raw_offset: 21600,
    timezone: 'Asia/Dhaka',
    utc_offset: '+06:00',
  },
  'Asia/Dili': {
    abbr: '+09',
    raw_offset: 32400,
    timezone: 'Asia/Dili',
    utc_offset: '+09:00',
  },
  'Asia/Dubai': {
    abbr: '+04',
    raw_offset: 14400,
    timezone: 'Asia/Dubai',
    utc_offset: '+04:00',
  },
  'Asia/Dushanbe': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Asia/Dushanbe',
    utc_offset: '+05:00',
  },
  'Asia/Famagusta': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Asia/Famagusta',
    utc_offset: '+03:00',
  },
  'Asia/Gaza': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Asia/Gaza',
    utc_offset: '+03:00',
  },
  'Asia/Hebron': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Asia/Hebron',
    utc_offset: '+03:00',
  },
  'Asia/Ho_Chi_Minh': {
    abbr: '+07',
    raw_offset: 25200,
    timezone: 'Asia/Ho_Chi_Minh',
    utc_offset: '+07:00',
  },
  'Asia/Hong_Kong': {
    abbr: 'HKT',
    raw_offset: 28800,
    timezone: 'Asia/Hong_Kong',
    utc_offset: '+08:00',
  },
  'Asia/Hovd': {
    abbr: '+07',
    raw_offset: 25200,
    timezone: 'Asia/Hovd',
    utc_offset: '+07:00',
  },
  'Asia/Irkutsk': {
    abbr: '+08',
    raw_offset: 28800,
    timezone: 'Asia/Irkutsk',
    utc_offset: '+08:00',
  },
  'Asia/Jakarta': {
    abbr: 'WIB',
    raw_offset: 25200,
    timezone: 'Asia/Jakarta',
    utc_offset: '+07:00',
  },
  'Asia/Jayapura': {
    abbr: 'WIT',
    raw_offset: 32400,
    timezone: 'Asia/Jayapura',
    utc_offset: '+09:00',
  },
  'Asia/Jerusalem': {
    abbr: 'IDT',
    raw_offset: 7200,
    timezone: 'Asia/Jerusalem',
    utc_offset: '+03:00',
  },
  'Asia/Kabul': {
    abbr: '+0430',
    raw_offset: 16200,
    timezone: 'Asia/Kabul',
    utc_offset: '+04:30',
  },
  'Asia/Kamchatka': {
    abbr: '+12',
    raw_offset: 43200,
    timezone: 'Asia/Kamchatka',
    utc_offset: '+12:00',
  },
  'Asia/Karachi': {
    abbr: 'PKT',
    raw_offset: 18000,
    timezone: 'Asia/Karachi',
    utc_offset: '+05:00',
  },
  'Asia/Kathmandu': {
    abbr: '+0545',
    raw_offset: 20700,
    timezone: 'Asia/Kathmandu',
    utc_offset: '+05:45',
  },
  'Asia/Khandyga': {
    abbr: '+09',
    raw_offset: 32400,
    timezone: 'Asia/Khandyga',
    utc_offset: '+09:00',
  },
  'Asia/Kolkata': {
    abbr: 'IST',
    raw_offset: 19800,
    timezone: 'Asia/Kolkata',
    utc_offset: '+05:30',
  },
  'Asia/Krasnoyarsk': {
    abbr: '+07',
    raw_offset: 25200,
    timezone: 'Asia/Krasnoyarsk',
    utc_offset: '+07:00',
  },
  'Asia/Kuching': {
    abbr: '+08',
    raw_offset: 28800,
    timezone: 'Asia/Kuching',
    utc_offset: '+08:00',
  },
  'Asia/Macau': {
    abbr: 'CST',
    raw_offset: 28800,
    timezone: 'Asia/Macau',
    utc_offset: '+08:00',
  },
  'Asia/Magadan': {
    abbr: '+11',
    raw_offset: 39600,
    timezone: 'Asia/Magadan',
    utc_offset: '+11:00',
  },
  'Asia/Makassar': {
    abbr: 'WITA',
    raw_offset: 28800,
    timezone: 'Asia/Makassar',
    utc_offset: '+08:00',
  },
  'Asia/Manila': {
    abbr: 'PST',
    raw_offset: 28800,
    timezone: 'Asia/Manila',
    utc_offset: '+08:00',
  },
  'Asia/Nicosia': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Asia/Nicosia',
    utc_offset: '+03:00',
  },
  'Asia/Novokuznetsk': {
    abbr: '+07',
    raw_offset: 25200,
    timezone: 'Asia/Novokuznetsk',
    utc_offset: '+07:00',
  },
  'Asia/Novosibirsk': {
    abbr: '+07',
    raw_offset: 25200,
    timezone: 'Asia/Novosibirsk',
    utc_offset: '+07:00',
  },
  'Asia/Omsk': {
    abbr: '+06',
    raw_offset: 21600,
    timezone: 'Asia/Omsk',
    utc_offset: '+06:00',
  },
  'Asia/Oral': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Asia/Oral',
    utc_offset: '+05:00',
  },
  'Asia/Pontianak': {
    abbr: 'WIB',
    raw_offset: 25200,
    timezone: 'Asia/Pontianak',
    utc_offset: '+07:00',
  },
  'Asia/Pyongyang': {
    abbr: 'KST',
    raw_offset: 32400,
    timezone: 'Asia/Pyongyang',
    utc_offset: '+09:00',
  },
  'Asia/Qatar': {
    abbr: '+03',
    raw_offset: 10800,
    timezone: 'Asia/Qatar',
    utc_offset: '+03:00',
  },
  'Asia/Qostanay': {
    abbr: '+06',
    raw_offset: 21600,
    timezone: 'Asia/Qostanay',
    utc_offset: '+06:00',
  },
  'Asia/Qyzylorda': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Asia/Qyzylorda',
    utc_offset: '+05:00',
  },
  'Asia/Riyadh': {
    abbr: '+03',
    raw_offset: 10800,
    timezone: 'Asia/Riyadh',
    utc_offset: '+03:00',
  },
  'Asia/Sakhalin': {
    abbr: '+11',
    raw_offset: 39600,
    timezone: 'Asia/Sakhalin',
    utc_offset: '+11:00',
  },
  'Asia/Samarkand': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Asia/Samarkand',
    utc_offset: '+05:00',
  },
  'Asia/Seoul': {
    abbr: 'KST',
    raw_offset: 32400,
    timezone: 'Asia/Seoul',
    utc_offset: '+09:00',
  },
  'Asia/Shanghai': {
    abbr: 'CST',
    raw_offset: 28800,
    timezone: 'Asia/Shanghai',
    utc_offset: '+08:00',
  },
  'Asia/Singapore': {
    abbr: '+08',
    raw_offset: 28800,
    timezone: 'Asia/Singapore',
    utc_offset: '+08:00',
  },
  'Asia/Srednekolymsk': {
    abbr: '+11',
    raw_offset: 39600,
    timezone: 'Asia/Srednekolymsk',
    utc_offset: '+11:00',
  },
  'Asia/Taipei': {
    abbr: 'CST',
    raw_offset: 28800,
    timezone: 'Asia/Taipei',
    utc_offset: '+08:00',
  },
  'Asia/Tashkent': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Asia/Tashkent',
    utc_offset: '+05:00',
  },
  'Asia/Tbilisi': {
    abbr: '+04',
    raw_offset: 14400,
    timezone: 'Asia/Tbilisi',
    utc_offset: '+04:00',
  },
  'Asia/Tehran': {
    abbr: '+0330',
    raw_offset: 12600,
    timezone: 'Asia/Tehran',
    utc_offset: '+03:30',
  },
  'Asia/Thimphu': {
    abbr: '+06',
    raw_offset: 21600,
    timezone: 'Asia/Thimphu',
    utc_offset: '+06:00',
  },
  'Asia/Tokyo': {
    abbr: 'JST',
    raw_offset: 32400,
    timezone: 'Asia/Tokyo',
    utc_offset: '+09:00',
  },
  'Asia/Tomsk': {
    abbr: '+07',
    raw_offset: 25200,
    timezone: 'Asia/Tomsk',
    utc_offset: '+07:00',
  },
  'Asia/Ulaanbaatar': {
    abbr: '+08',
    raw_offset: 28800,
    timezone: 'Asia/Ulaanbaatar',
    utc_offset: '+08:00',
  },
  'Asia/Urumqi': {
    abbr: '+06',
    raw_offset: 21600,
    timezone: 'Asia/Urumqi',
    utc_offset: '+06:00',
  },
  'Asia/Ust-Nera': {
    abbr: '+10',
    raw_offset: 36000,
    timezone: 'Asia/Ust-Nera',
    utc_offset: '+10:00',
  },
  'Asia/Vladivostok': {
    abbr: '+10',
    raw_offset: 36000,
    timezone: 'Asia/Vladivostok',
    utc_offset: '+10:00',
  },
  'Asia/Yakutsk': {
    abbr: '+09',
    raw_offset: 32400,
    timezone: 'Asia/Yakutsk',
    utc_offset: '+09:00',
  },
  'Asia/Yangon': {
    abbr: '+0630',
    raw_offset: 23400,
    timezone: 'Asia/Yangon',
    utc_offset: '+06:30',
  },
  'Asia/Yekaterinburg': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Asia/Yekaterinburg',
    utc_offset: '+05:00',
  },
  'Asia/Yerevan': {
    abbr: '+04',
    raw_offset: 14400,
    timezone: 'Asia/Yerevan',
    utc_offset: '+04:00',
  },
  'Atlantic/Azores': {
    abbr: '+00',
    raw_offset: -3600,
    timezone: 'Atlantic/Azores',
    utc_offset: '+00:00',
  },
  'Atlantic/Bermuda': {
    abbr: 'ADT',
    raw_offset: -14400,
    timezone: 'Atlantic/Bermuda',
    utc_offset: '-03:00',
  },
  'Atlantic/Canary': {
    abbr: 'WEST',
    raw_offset: 0,
    timezone: 'Atlantic/Canary',
    utc_offset: '+01:00',
  },
  'Atlantic/Cape_Verde': {
    abbr: '-01',
    raw_offset: -3600,
    timezone: 'Atlantic/Cape_Verde',
    utc_offset: '-01:00',
  },
  'Atlantic/Faroe': {
    abbr: 'WEST',
    raw_offset: 0,
    timezone: 'Atlantic/Faroe',
    utc_offset: '+01:00',
  },
  'Atlantic/Madeira': {
    abbr: 'WEST',
    raw_offset: 0,
    timezone: 'Atlantic/Madeira',
    utc_offset: '+01:00',
  },
  'Atlantic/South_Georgia': {
    abbr: '-02',
    raw_offset: -7200,
    timezone: 'Atlantic/South_Georgia',
    utc_offset: '-02:00',
  },
  'Atlantic/Stanley': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'Atlantic/Stanley',
    utc_offset: '-03:00',
  },
  'Australia/Adelaide': {
    abbr: 'ACST',
    raw_offset: 34200,
    timezone: 'Australia/Adelaide',
    utc_offset: '+09:30',
  },
  'Australia/Brisbane': {
    abbr: 'AEST',
    raw_offset: 36000,
    timezone: 'Australia/Brisbane',
    utc_offset: '+10:00',
  },
  'Australia/Broken_Hill': {
    abbr: 'ACST',
    raw_offset: 34200,
    timezone: 'Australia/Broken_Hill',
    utc_offset: '+09:30',
  },
  'Australia/Darwin': {
    abbr: 'ACST',
    raw_offset: 34200,
    timezone: 'Australia/Darwin',
    utc_offset: '+09:30',
  },
  'Australia/Eucla': {
    abbr: '+0845',
    raw_offset: 31500,
    timezone: 'Australia/Eucla',
    utc_offset: '+08:45',
  },
  'Australia/Hobart': {
    abbr: 'AEST',
    raw_offset: 36000,
    timezone: 'Australia/Hobart',
    utc_offset: '+10:00',
  },
  'Australia/Lindeman': {
    abbr: 'AEST',
    raw_offset: 36000,
    timezone: 'Australia/Lindeman',
    utc_offset: '+10:00',
  },
  'Australia/Lord_Howe': {
    abbr: '+1030',
    raw_offset: 37800,
    timezone: 'Australia/Lord_Howe',
    utc_offset: '+10:30',
  },
  'Australia/Melbourne': {
    abbr: 'AEST',
    raw_offset: 36000,
    timezone: 'Australia/Melbourne',
    utc_offset: '+10:00',
  },
  'Australia/Perth': {
    abbr: 'AWST',
    raw_offset: 28800,
    timezone: 'Australia/Perth',
    utc_offset: '+08:00',
  },
  'Australia/Sydney': {
    abbr: 'AEST',
    raw_offset: 36000,
    timezone: 'Australia/Sydney',
    utc_offset: '+10:00',
  },
  CET: {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'CET',
    utc_offset: '+02:00',
  },
  CST6CDT: {
    abbr: 'CDT',
    raw_offset: -21600,
    timezone: 'CST6CDT',
    utc_offset: '-05:00',
  },
  EET: {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'EET',
    utc_offset: '+03:00',
  },
  EST: {
    abbr: 'EST',
    raw_offset: -18000,
    timezone: 'EST',
    utc_offset: '-05:00',
  },
  EST5EDT: {
    abbr: 'EDT',
    raw_offset: -18000,
    timezone: 'EST5EDT',
    utc_offset: '-04:00',
  },
  'Etc/GMT': {
    abbr: 'GMT',
    raw_offset: 0,
    timezone: 'Etc/GMT',
    utc_offset: '+00:00',
  },
  'Etc/GMT+1': {
    abbr: '-01',
    raw_offset: -3600,
    timezone: 'Etc/GMT+1',
    utc_offset: '-01:00',
  },
  'Etc/GMT+10': {
    abbr: '-10',
    raw_offset: -36000,
    timezone: 'Etc/GMT+10',
    utc_offset: '-10:00',
  },
  'Etc/GMT+11': {
    abbr: '-11',
    raw_offset: -39600,
    timezone: 'Etc/GMT+11',
    utc_offset: '-11:00',
  },
  'Etc/GMT+12': {
    abbr: '-12',
    raw_offset: -43200,
    timezone: 'Etc/GMT+12',
    utc_offset: '-12:00',
  },
  'Etc/GMT+2': {
    abbr: '-02',
    raw_offset: -7200,
    timezone: 'Etc/GMT+2',
    utc_offset: '-02:00',
  },
  'Etc/GMT+3': {
    abbr: '-03',
    raw_offset: -10800,
    timezone: 'Etc/GMT+3',
    utc_offset: '-03:00',
  },
  'Etc/GMT+4': {
    abbr: '-04',
    raw_offset: -14400,
    timezone: 'Etc/GMT+4',
    utc_offset: '-04:00',
  },
  'Etc/GMT+5': {
    abbr: '-05',
    raw_offset: -18000,
    timezone: 'Etc/GMT+5',
    utc_offset: '-05:00',
  },
  'Etc/GMT+6': {
    abbr: '-06',
    raw_offset: -21600,
    timezone: 'Etc/GMT+6',
    utc_offset: '-06:00',
  },
  'Etc/GMT+7': {
    abbr: '-07',
    raw_offset: -25200,
    timezone: 'Etc/GMT+7',
    utc_offset: '-07:00',
  },
  'Etc/GMT+8': {
    abbr: '-08',
    raw_offset: -28800,
    timezone: 'Etc/GMT+8',
    utc_offset: '-08:00',
  },
  'Etc/GMT+9': {
    abbr: '-09',
    raw_offset: -32400,
    timezone: 'Etc/GMT+9',
    utc_offset: '-09:00',
  },
  'Etc/GMT-1': {
    abbr: '+01',
    raw_offset: 3600,
    timezone: 'Etc/GMT-1',
    utc_offset: '+01:00',
  },
  'Etc/GMT-10': {
    abbr: '+10',
    raw_offset: 36000,
    timezone: 'Etc/GMT-10',
    utc_offset: '+10:00',
  },
  'Etc/GMT-11': {
    abbr: '+11',
    raw_offset: 39600,
    timezone: 'Etc/GMT-11',
    utc_offset: '+11:00',
  },
  'Etc/GMT-12': {
    abbr: '+12',
    raw_offset: 43200,
    timezone: 'Etc/GMT-12',
    utc_offset: '+12:00',
  },
  'Etc/GMT-13': {
    abbr: '+13',
    raw_offset: 46800,
    timezone: 'Etc/GMT-13',
    utc_offset: '+13:00',
  },
  'Etc/GMT-14': {
    abbr: '+14',
    raw_offset: 50400,
    timezone: 'Etc/GMT-14',
    utc_offset: '+14:00',
  },
  'Etc/GMT-2': {
    abbr: '+02',
    raw_offset: 7200,
    timezone: 'Etc/GMT-2',
    utc_offset: '+02:00',
  },
  'Etc/GMT-3': {
    abbr: '+03',
    raw_offset: 10800,
    timezone: 'Etc/GMT-3',
    utc_offset: '+03:00',
  },
  'Etc/GMT-4': {
    abbr: '+04',
    raw_offset: 14400,
    timezone: 'Etc/GMT-4',
    utc_offset: '+04:00',
  },
  'Etc/GMT-5': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Etc/GMT-5',
    utc_offset: '+05:00',
  },
  'Etc/GMT-6': {
    abbr: '+06',
    raw_offset: 21600,
    timezone: 'Etc/GMT-6',
    utc_offset: '+06:00',
  },
  'Etc/GMT-7': {
    abbr: '+07',
    raw_offset: 25200,
    timezone: 'Etc/GMT-7',
    utc_offset: '+07:00',
  },
  'Etc/GMT-8': {
    abbr: '+08',
    raw_offset: 28800,
    timezone: 'Etc/GMT-8',
    utc_offset: '+08:00',
  },
  'Etc/GMT-9': {
    abbr: '+09',
    raw_offset: 32400,
    timezone: 'Etc/GMT-9',
    utc_offset: '+09:00',
  },
  'Etc/UTC': {
    abbr: 'UTC',
    raw_offset: 0,
    timezone: 'Etc/UTC',
    utc_offset: '+00:00',
  },
  'Europe/Andorra': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Andorra',
    utc_offset: '+02:00',
  },
  'Europe/Astrakhan': {
    abbr: '+04',
    raw_offset: 14400,
    timezone: 'Europe/Astrakhan',
    utc_offset: '+04:00',
  },
  'Europe/Athens': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Europe/Athens',
    utc_offset: '+03:00',
  },
  'Europe/Belgrade': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Belgrade',
    utc_offset: '+02:00',
  },
  'Europe/Berlin': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Berlin',
    utc_offset: '+02:00',
  },
  'Europe/Brussels': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Brussels',
    utc_offset: '+02:00',
  },
  'Europe/Bucharest': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Europe/Bucharest',
    utc_offset: '+03:00',
  },
  'Europe/Budapest': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Budapest',
    utc_offset: '+02:00',
  },
  'Europe/Chisinau': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Europe/Chisinau',
    utc_offset: '+03:00',
  },
  'Europe/Dublin': {
    abbr: 'IST',
    raw_offset: 3600,
    timezone: 'Europe/Dublin',
    utc_offset: '+01:00',
  },
  'Europe/Gibraltar': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Gibraltar',
    utc_offset: '+02:00',
  },
  'Europe/Helsinki': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Europe/Helsinki',
    utc_offset: '+03:00',
  },
  'Europe/Istanbul': {
    abbr: '+03',
    raw_offset: 10800,
    timezone: 'Europe/Istanbul',
    utc_offset: '+03:00',
  },
  'Europe/Kaliningrad': {
    abbr: 'EET',
    raw_offset: 7200,
    timezone: 'Europe/Kaliningrad',
    utc_offset: '+02:00',
  },
  'Europe/Kirov': {
    abbr: 'MSK',
    raw_offset: 10800,
    timezone: 'Europe/Kirov',
    utc_offset: '+03:00',
  },
  'Europe/Kyiv': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Europe/Kyiv',
    utc_offset: '+03:00',
  },
  'Europe/Lisbon': {
    abbr: 'WEST',
    raw_offset: 0,
    timezone: 'Europe/Lisbon',
    utc_offset: '+01:00',
  },
  'Europe/London': {
    abbr: 'BST',
    raw_offset: 0,
    timezone: 'Europe/London',
    utc_offset: '+01:00',
  },
  'Europe/Madrid': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Madrid',
    utc_offset: '+02:00',
  },
  'Europe/Malta': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Malta',
    utc_offset: '+02:00',
  },
  'Europe/Minsk': {
    abbr: '+03',
    raw_offset: 10800,
    timezone: 'Europe/Minsk',
    utc_offset: '+03:00',
  },
  'Europe/Moscow': {
    abbr: 'MSK',
    raw_offset: 10800,
    timezone: 'Europe/Moscow',
    utc_offset: '+03:00',
  },
  'Europe/Paris': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Paris',
    utc_offset: '+02:00',
  },
  'Europe/Prague': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Prague',
    utc_offset: '+02:00',
  },
  'Europe/Riga': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Europe/Riga',
    utc_offset: '+03:00',
  },
  'Europe/Rome': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Rome',
    utc_offset: '+02:00',
  },
  'Europe/Samara': {
    abbr: '+04',
    raw_offset: 14400,
    timezone: 'Europe/Samara',
    utc_offset: '+04:00',
  },
  'Europe/Saratov': {
    abbr: '+04',
    raw_offset: 14400,
    timezone: 'Europe/Saratov',
    utc_offset: '+04:00',
  },
  'Europe/Simferopol': {
    abbr: 'MSK',
    raw_offset: 10800,
    timezone: 'Europe/Simferopol',
    utc_offset: '+03:00',
  },
  'Europe/Sofia': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Europe/Sofia',
    utc_offset: '+03:00',
  },
  'Europe/Tallinn': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Europe/Tallinn',
    utc_offset: '+03:00',
  },
  'Europe/Tirane': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Tirane',
    utc_offset: '+02:00',
  },
  'Europe/Ulyanovsk': {
    abbr: '+04',
    raw_offset: 14400,
    timezone: 'Europe/Ulyanovsk',
    utc_offset: '+04:00',
  },
  'Europe/Vienna': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Vienna',
    utc_offset: '+02:00',
  },
  'Europe/Vilnius': {
    abbr: 'EEST',
    raw_offset: 7200,
    timezone: 'Europe/Vilnius',
    utc_offset: '+03:00',
  },
  'Europe/Volgograd': {
    abbr: 'MSK',
    raw_offset: 10800,
    timezone: 'Europe/Volgograd',
    utc_offset: '+03:00',
  },
  'Europe/Warsaw': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Warsaw',
    utc_offset: '+02:00',
  },
  'Europe/Zurich': {
    abbr: 'CEST',
    raw_offset: 3600,
    timezone: 'Europe/Zurich',
    utc_offset: '+02:00',
  },
  HST: {
    abbr: 'HST',
    raw_offset: -36000,
    timezone: 'HST',
    utc_offset: '-10:00',
  },
  'Indian/Chagos': {
    abbr: '+06',
    raw_offset: 21600,
    timezone: 'Indian/Chagos',
    utc_offset: '+06:00',
  },
  'Indian/Maldives': {
    abbr: '+05',
    raw_offset: 18000,
    timezone: 'Indian/Maldives',
    utc_offset: '+05:00',
  },
  'Indian/Mauritius': {
    abbr: '+04',
    raw_offset: 14400,
    timezone: 'Indian/Mauritius',
    utc_offset: '+04:00',
  },
  MET: {
    abbr: 'MEST',
    raw_offset: 3600,
    timezone: 'MET',
    utc_offset: '+02:00',
  },
  MST: {
    abbr: 'MST',
    raw_offset: -25200,
    timezone: 'MST',
    utc_offset: '-07:00',
  },
  MST7MDT: {
    abbr: 'MDT',
    raw_offset: -25200,
    timezone: 'MST7MDT',
    utc_offset: '-06:00',
  },
  PST8PDT: {
    abbr: 'PDT',
    raw_offset: -28800,
    timezone: 'PST8PDT',
    utc_offset: '-07:00',
  },
  'Pacific/Apia': {
    abbr: '+13',
    raw_offset: 46800,
    timezone: 'Pacific/Apia',
    utc_offset: '+13:00',
  },
  'Pacific/Auckland': {
    abbr: 'NZST',
    raw_offset: 43200,
    timezone: 'Pacific/Auckland',
    utc_offset: '+12:00',
  },
  'Pacific/Bougainville': {
    abbr: '+11',
    raw_offset: 39600,
    timezone: 'Pacific/Bougainville',
    utc_offset: '+11:00',
  },
  'Pacific/Chatham': {
    abbr: '+1245',
    raw_offset: 45900,
    timezone: 'Pacific/Chatham',
    utc_offset: '+12:45',
  },
  'Pacific/Easter': {
    abbr: '-06',
    raw_offset: -21600,
    timezone: 'Pacific/Easter',
    utc_offset: '-06:00',
  },
  'Pacific/Efate': {
    abbr: '+11',
    raw_offset: 39600,
    timezone: 'Pacific/Efate',
    utc_offset: '+11:00',
  },
  'Pacific/Fakaofo': {
    abbr: '+13',
    raw_offset: 46800,
    timezone: 'Pacific/Fakaofo',
    utc_offset: '+13:00',
  },
  'Pacific/Fiji': {
    abbr: '+12',
    raw_offset: 43200,
    timezone: 'Pacific/Fiji',
    utc_offset: '+12:00',
  },
  'Pacific/Galapagos': {
    abbr: '-06',
    raw_offset: -21600,
    timezone: 'Pacific/Galapagos',
    utc_offset: '-06:00',
  },
  'Pacific/Gambier': {
    abbr: '-09',
    raw_offset: -32400,
    timezone: 'Pacific/Gambier',
    utc_offset: '-09:00',
  },
  'Pacific/Guadalcanal': {
    abbr: '+11',
    raw_offset: 39600,
    timezone: 'Pacific/Guadalcanal',
    utc_offset: '+11:00',
  },
  'Pacific/Guam': {
    abbr: 'ChST',
    raw_offset: 36000,
    timezone: 'Pacific/Guam',
    utc_offset: '+10:00',
  },
  'Pacific/Honolulu': {
    abbr: 'HST',
    raw_offset: -36000,
    timezone: 'Pacific/Honolulu',
    utc_offset: '-10:00',
  },
  'Pacific/Kanton': {
    abbr: '+13',
    raw_offset: 46800,
    timezone: 'Pacific/Kanton',
    utc_offset: '+13:00',
  },
  'Pacific/Kiritimati': {
    abbr: '+14',
    raw_offset: 50400,
    timezone: 'Pacific/Kiritimati',
    utc_offset: '+14:00',
  },
  'Pacific/Kosrae': {
    abbr: '+11',
    raw_offset: 39600,
    timezone: 'Pacific/Kosrae',
    utc_offset: '+11:00',
  },
  'Pacific/Kwajalein': {
    abbr: '+12',
    raw_offset: 43200,
    timezone: 'Pacific/Kwajalein',
    utc_offset: '+12:00',
  },
  'Pacific/Marquesas': {
    abbr: '-0930',
    raw_offset: -34200,
    timezone: 'Pacific/Marquesas',
    utc_offset: '-09:30',
  },
  'Pacific/Nauru': {
    abbr: '+12',
    raw_offset: 43200,
    timezone: 'Pacific/Nauru',
    utc_offset: '+12:00',
  },
  'Pacific/Niue': {
    abbr: '-11',
    raw_offset: -39600,
    timezone: 'Pacific/Niue',
    utc_offset: '-11:00',
  },
  'Pacific/Norfolk': {
    abbr: '+11',
    raw_offset: 39600,
    timezone: 'Pacific/Norfolk',
    utc_offset: '+11:00',
  },
  'Pacific/Noumea': {
    abbr: '+11',
    raw_offset: 39600,
    timezone: 'Pacific/Noumea',
    utc_offset: '+11:00',
  },
  'Pacific/Pago_Pago': {
    abbr: 'SST',
    raw_offset: -39600,
    timezone: 'Pacific/Pago_Pago',
    utc_offset: '-11:00',
  },
  'Pacific/Palau': {
    abbr: '+09',
    raw_offset: 32400,
    timezone: 'Pacific/Palau',
    utc_offset: '+09:00',
  },
  'Pacific/Pitcairn': {
    abbr: '-08',
    raw_offset: -28800,
    timezone: 'Pacific/Pitcairn',
    utc_offset: '-08:00',
  },
  'Pacific/Port_Moresby': {
    abbr: '+10',
    raw_offset: 36000,
    timezone: 'Pacific/Port_Moresby',
    utc_offset: '+10:00',
  },
  'Pacific/Rarotonga': {
    abbr: '-10',
    raw_offset: -36000,
    timezone: 'Pacific/Rarotonga',
    utc_offset: '-10:00',
  },
  'Pacific/Tahiti': {
    abbr: '-10',
    raw_offset: -36000,
    timezone: 'Pacific/Tahiti',
    utc_offset: '-10:00',
  },
  'Pacific/Tarawa': {
    abbr: '+12',
    raw_offset: 43200,
    timezone: 'Pacific/Tarawa',
    utc_offset: '+12:00',
  },
  'Pacific/Tongatapu': {
    abbr: '+13',
    raw_offset: 46800,
    timezone: 'Pacific/Tongatapu',
    utc_offset: '+13:00',
  },
  WET: {
    abbr: 'WEST',
    raw_offset: 0,
    timezone: 'WET',
    utc_offset: '+01:00',
  },
}
