export enum ResellingRewardMemoType {
  GENERAL = 'GENERAL',
  BAN_RESELLER = 'BAN_RESELLER',
  REJECT_PAYOUT = 'REJECT_PAYOUT',
  REINSTATE_PAYOUT = 'REINSTATE_PAYOUT',
  REINSTATE_RESELLER = 'REINSTATE_RESELLER',
}
