import { UserTypes } from '@app/shared/enums'

export enum AccountType {
  NONPROFIT = UserTypes.NONPROFIT,
  RE2 = UserTypes.RE2,
  ADMIN = UserTypes.ADMIN,
  INDIVIDUAL_PERSONAL = UserTypes.INDIVIDUAL_PERSONAL,
  INDIVIDUAL_INFLUENCER = UserTypes.INDIVIDUAL_INFLUENCER,
  BUSINESS_SOLE_PROPRIETOR = UserTypes.BUSINESS_SOLE_PROPRIETOR,
  BUSINESS_COMPANY = UserTypes.BUSINESS_COMPANY,
}
