version: '3.8'

volumes:
  db:

networks:
  default:
    name: ${DOCKER_NETWORK}

services:
  dev:
    container_name: ${DOCKER_CONTAINER_NAME}_${NODE_ENV}
    image: ${DOCKER_CONTAINER_NAME}-${NODE_ENV}:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - default
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_started
  prod:
    container_name: ${DOCKER_CONTAINER_NAME}_${NODE_ENV}
    image: ${DOCKER_CONTAINER_NAME}-${NODE_ENV}:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    env_file:
      - .env
    networks:
      - default
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_started
  db:
    container_name: ${DOCKER_CONTAINER_NAME}_pgdb
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT_WERBOSE}:${TYPEORM_PORT}
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  migration:
    container_name: ${DOCKER_CONTAINER_NAME}_migration
    image: ${DOCKER_CONTAINER_NAME}-${NODE_ENV}:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    command: npm run migration:run
