export enum DeliverySettingsType {
  GENERAL = 'GENERAL',
  UNATTENDED = 'UNATTENDED',
  PRODUCT_TAG = 'PRODUCT_TAG',
  PREFERENCES_BY_DESTINATION = 'PREFERENCES_BY_DESTINATION',
  DISABLE_DELIVERY_DATE = 'DISABLE_DELIVERY_DATE',
}
