export enum StarActionType {
  // Transaction based stars
  SALE_RAFFLE = 'SALE_RAFFLE',
  SALE_BUYNOW = 'SALE_BUYNOW',
  SALE_AUCTION = 'SALE_AUCTION',
  RESALE_BUYNOW = 'RESALE_BUYNOW',
  PURCHASE_RAFFLE = 'PURCHASE_RAFFLE',
  PURCHASE_BUYNOW = 'PURCHASE_BUYNOW',
  PURCHASE_AUCTION = 'PURCHASE_AUCTION',

  // Donation based stars
  RE2_DONATION = 'RE2_DONATION',
  DONATION_BUYNOW = 'DONATION_BUYNOW',
  DIRECT_DONATION = 'DIRECT_DONATION',
  DONATION_RAFFLE = 'DONATION_RAFFLE',
  RESALE_DONATION = 'RESALE_DONATION',
  DONATION_AUCTION = 'DONATION_AUCTION',

  // Contribution based stars
  SHARE_DEAL = 'SHARE_DEAL',
  RESALE_ORDER = 'RESALE_ORDER',
  INVITED_SALE = 'INVITED_SALE',
  FRIEND_INVITE = 'FRIEND_INVITE',
  ORDER_CREATED = 'ORDER_CREATED',
  SHARE_NONPROFIT = 'SHARE_NONPROFIT',
  SHARE_FUNDRAISER = 'SHARE_FUNDRAISER',
  INVITED_PURCHASE = 'INVITED_PURCHASE',
  INVITED_RE2_DONATION = 'INVITED_RE2_DONATION',
  SHARE_DONATION_PROJECT = 'SHARE_DONATION_PROJECT',
  INVITED_DIRECT_DONATION = 'INVITED_DIRECT_DONATION',
}
