export enum DONATION_SOURCE {
  DIRECT = 'DIRECT',
  RECURRING = 'RECURRING',
  FUNDRAISER_FORM = 'FUNDRAISER_FORM',
  FUNDRAISER_PAGE = 'FUNDRAISER_PAGE',
  INTEGRATION_CART_BANNER = 'INTEGRATION_CART_BANNER',
  INTEGRATION_CART_DRAWER = 'INTEGRATION_CART_DRAWER',
  INTEGRATION_SALES_PORTION = 'INTEGRATION_SALES_PORTION',
}
