export enum PAYMENT_STATUS {
  REVERTED = 'REVERTED',
  REFUNDED = 'REFUNDED',
  INITIATED = 'INITIATED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DONATION_SETTLED = 'DONATION_SETTLED',
}
