export enum POINTS_REASON {
  DEAL = 'DEAL',
  REDEEM = 'REDEEM',
  DONATION = 'DONATION',
  RESELLING = 'RESELLING',
  REDEEM_REVERT = 'REDEEM_REVERT',
  RE2_FUNDRAISER = 'RE2_FUNDRAISER',
  REDEEM_COMPLETE = 'REDEEM_COMPLETE',
  RE2_SHOPIFY_INTEGRATION = 'RE2_SHOPIFY_INTEGRATION',
  DEAL_PAYMENT_REDEMPTION = 'DEAL_PAYMENT_REDEMPTION',
}

export enum POINTS_STATUS {
  LOCKED = 'LOCKED',
  EXPIRED = 'EXPIRED',
  REDEEMED = 'REDEEMED',
  REVERTED = 'REVERTED',
  UNLOCKED = 'UNLOCKED',
  DELIVERED = 'DELIVERED',
  PARTIALLY_REDEEMED = 'PARTIALLY_REDEEMED',
  AWAITING_WITHDRAWAL = 'AWAITING_WITHDRAWAL',
  LOCKED_FOR_REDEMPTION = 'LOCKED_FOR_REDEMPTION',
  LOCKED_FOR_DEAL_PAYMENT = 'LOCKED_FOR_DEAL_PAYMENT',
}

export enum POINTS_TYPE {
  GAS = 'GAS',
  DEAL = 'DEAL',
  REDEEM = 'REDEEM',
  DONATION = 'DONATION',
  RESELLING = 'RESELLING',
  SHOPIFY_INTEGRATION = 'SHOPIFY_INTEGRATION',
}
