export enum OrderRoutingType {
  SHIP_FROM_CLOSEST_LOCATION = 'SHIP_FROM_CLOSEST_LOCATION',
  USE_RANKED_SHIPPING_ORIGINS = 'USE_RANKED_SHIPPING_ORIGINS',
  MINIMIZE_SPLIT_FULFILLMENTS = 'MINIMIZE_SPLIT_FULFILLMENTS',
}
