import { Types } from '@app/src/shared/enums'

export enum DonationType {
  RAFFLE = Types.RAFFLE,
  BUYNOW = Types.BUYNOW,
  SHOPIFY = Types.SHOPIFY,
  AUCTION = Types.AUCTION,
  DIRECT_DONATION = Types.DIRECT_DONATION,
  FUNDRAISER_FORM = Types.FUNDRAISER_FORM,
  FUNDRAISER_PAGE = Types.FUNDRAISER_PAGE,
  INTEGRATION_CART_BANNER = Types.INTEGRATION_CART_BANNER,
  INTEGRATION_CART_DRAWER = Types.INTEGRATION_CART_DRAWER,
  INTEGRATION_SALES_PORTION = Types.INTEGRATION_SALES_PORTION,
}
