export enum DONATION_REASON {
  DEAL = 'DEAL',
  DONATION = 'DONATION',
}

export enum DONATION_STATUS {
  INITIATED = 'INITIATED',
  COMPLETED = 'COMPLETED',
  SETTLED = 'SETTLED',
  CANCELLED = 'CANCELLED',
  REVERTED = 'REVERTED',
  REFUNDED = 'REFUNDED',
}
