import { Query } from '@app/src/shared/enums'

export enum IncludesQuery {
  CONTINENT = Query.CONTINENT,
  PROVINCE = Query.PROVINCES,
  TRANSLATIONS = Query.TRANSLATIONS,
  TRANSLATIONS_LANGUAGE = Query.TRANSLATIONS_LANGUAGE,
  PROVINCE_TRANSLATIONS = Query.PROVINCES_TRANSLATIONS,
  CONTINENT_TRANSLATIONS = Query.CONTINENT_TRANSLATIONS,
}
