export enum SettingName {
  COUNTRY = 'COUNTRY',
  TIMEZONE = 'TIMEZONE',
  LANGUAGE = 'LANGUAGE',
  STABLE_COIN = 'STABLE_COIN',
  FIAT_CURRENCY = 'FIAT_CURRENCY',
  LOGIN_ENABLED = 'LOGIN_ENABLED',
  SIGNUP_ENABLED = 'SIGNUP_ENABLED',
  RAFFLE_ENABLED = 'RAFFLE_ENABLED',
  ACT_ON_SPECIFIED_COMMERCIAL = 'ACT_ON_SPECIFIED_COMMERCIAL',
  BASE_CURRENCY = 'BASE_CURRENCY',
}
