export enum FrequencyOfOccurrence {
  EVERYTIME = 'EVERYTIME',
  ONCE_EVERY_3_TIMES = 'ONCE_EVERY_3_TIMES',
  ONCE_EVERY_5_TIMES = 'ONCE_EVERY_5_TIMES',
  OCCASIONALLY = 'OCCASIONALLY',
  OTHER = 'OTHER',
}
