export enum SubTopicType {
  FOR_BEGINNERS = 'FOR_BEGINNERS',
  ASK_HOW_TO_USE = 'ASK_HOW_TO_USE',
  ASK_ABOUT_LISTING = 'ASK_ABOUT_LISTING',
  ASK_ABOUT_PURCHASES = 'ASK_ABOUT_PURCHASES',
  ASK_ABOUT_LISTED_PRODUCTS = 'ASK_ABOUT_LISTED_PRODUCTS',
  ASK_ABOUT_PRODUCT_DELIVERY = 'ASK_ABOUT_PRODUCT_DELIVERY',
}
