export enum TopicType {
  OTHER = 'OTHER',
  REPORT_BUG = 'REPORT_BUG',
  ORDER_RELATED = 'ORDER_RELATED',
  ABOUT_PROBLEM = 'ABOUT_PROBLEM',
  FOR_BEGINNERS = 'FOR_BEGINNERS',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  FEATURE_REQUEST = 'FEATURE_REQUEST',
  ABOUT_SHIPPING_REVIEW = 'ABOUT_SHIPPING_REVIEW',
  ABOUT_TRANSFER_REQUEST = 'ABOUT_TRANSFER_REQUEST',
  ABOUT_REGISTRATION_LOGIN = 'ABOUT_REGISTRATION_LOGIN',
  ABOUT_PURCHASE_AND_PAYMENT = 'ABOUT_PURCHASE_AND_PAYMENT',
}
