export default [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'MAX_BATCH_SIZE',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'NATIVE_TOKEN',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'batchWhitelist',
    inputs: [
      { name: 'brandId', type: 'uint256', internalType: 'uint256' },
      { name: 'users', type: 'address[]', internalType: 'address[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'btManager',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IBTManager' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cancelICO',
    inputs: [{ name: 'brandId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'checkEligibility',
    inputs: [
      { name: 'brandId', type: 'uint256', internalType: 'uint256' },
      { name: 'user', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'configureICO',
    inputs: [
      { name: 'brandId', type: 'uint256', internalType: 'uint256' },
      { name: 'startTime', type: 'uint256', internalType: 'uint256' },
      { name: 'endTime', type: 'uint256', internalType: 'uint256' },
      {
        name: 'minContribution',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'maxContribution',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'contribute',
    inputs: [
      { name: 'brandId', type: 'uint256', internalType: 'uint256' },
      {
        name: 'paymentToken',
        type: 'address',
        internalType: 'address',
      },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'path', type: 'address[]', internalType: 'address[]' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'contributions',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'claimed', type: 'bool', internalType: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'finalizeICO',
    inputs: [{ name: 'brandId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getWhitelistCriteria',
    inputs: [{ name: 'brandId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: 'minTokenHold',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'minStake', type: 'uint256', internalType: 'uint256' },
      { name: 'minLPHold', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getWhitelistStatus',
    inputs: [
      { name: 'brandId', type: 'uint256', internalType: 'uint256' },
      { name: 'user', type: 'address', internalType: 'address' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct ICOManager.WhitelistStatus',
        components: [
          { name: 'isWhitelisted', type: 'bool', internalType: 'bool' },
          {
            name: 'whitelistedAt',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'icoConfigs',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'brandId', type: 'uint256', internalType: 'uint256' },
      { name: 'startTime', type: 'uint256', internalType: 'uint256' },
      { name: 'endTime', type: 'uint256', internalType: 'uint256' },
      {
        name: 'minContribution',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'maxContribution',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'tokenAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'isInitialICO', type: 'bool', internalType: 'bool' },
      {
        name: 'status',
        type: 'uint8',
        internalType: 'enum ICOManager.ICOStatus',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'icoVault',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: '_btManager', type: 'address', internalType: 'address' },
      { name: '_icoVault', type: 'address', internalType: 'address' },
      { name: '_lpManager', type: 'address', internalType: 'address' },
      {
        name: '_tradeHandler',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'initializeICO',
    inputs: [
      { name: 'brandId', type: 'uint256', internalType: 'uint256' },
      { name: 'tokenAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'isInitialICO', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isICOAvailable',
    inputs: [{ name: 'brandId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isWhitelisted',
    inputs: [
      { name: 'brandId', type: 'uint256', internalType: 'uint256' },
      { name: 'user', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lpManager',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pauseICO',
    inputs: [{ name: 'brandId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proxiableUUID',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'removeFromWhitelist',
    inputs: [
      { name: 'brandId', type: 'uint256', internalType: 'uint256' },
      { name: 'user', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'resumeICO',
    inputs: [{ name: 'brandId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setWhitelistCriteria',
    inputs: [
      { name: 'brandId', type: 'uint256', internalType: 'uint256' },
      {
        name: 'minTokenHold',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'minStake', type: 'uint256', internalType: 'uint256' },
      { name: 'minLPHold', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'startICO',
    inputs: [{ name: 'brandId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'tokenContributions',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'claimed', type: 'bool', internalType: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalContributions',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalTokenContributions',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tradeHandler',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract ITradeHandler',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unpause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateBTManager',
    inputs: [{ name: '_btManager', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateICOVault',
    inputs: [{ name: '_icoVault', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'upgradeTo',
    inputs: [
      {
        name: 'newImplementation',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'upgradeToAndCall',
    inputs: [
      {
        name: 'newImplementation',
        type: 'address',
        internalType: 'address',
      },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'whitelistAddress',
    inputs: [
      { name: 'brandId', type: 'uint256', internalType: 'uint256' },
      { name: 'user', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'whitelistCount',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'whitelistCriteria',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: 'minTokenHold',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'minStake', type: 'uint256', internalType: 'uint256' },
      { name: 'minLPHold', type: 'uint256', internalType: 'uint256' },
      { name: 'isActive', type: 'bool', internalType: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'whitelistStatus',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [
      { name: 'isWhitelisted', type: 'bool', internalType: 'bool' },
      {
        name: 'whitelistedAt',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'withdrawContribution',
    inputs: [{ name: 'brandId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'AddressRemovedFromWhitelist',
    inputs: [
      {
        name: 'brandId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'timestamp',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'AddressWhitelisted',
    inputs: [
      {
        name: 'brandId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'automatic',
        type: 'bool',
        indexed: true,
        internalType: 'bool',
      },
      {
        name: 'timestamp',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'AdminChanged',
    inputs: [
      {
        name: 'previousAdmin',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'newAdmin',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BatchWhitelistAdded',
    inputs: [
      {
        name: 'brandId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'count',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'timestamp',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BatchWhitelistProcessed',
    inputs: [
      {
        name: 'brandId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'count',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BeaconUpgraded',
    inputs: [
      {
        name: 'beacon',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ContributionReceived',
    inputs: [
      {
        name: 'brandId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'contributor',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ICOCompleted',
    inputs: [
      {
        name: 'brandId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'totalRaised',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'distributedAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ICOConfigured',
    inputs: [
      {
        name: 'brandId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'startTime',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endTime',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'minContribution',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'maxContribution',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ICOInitialized',
    inputs: [
      {
        name: 'brandId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'isInitialICO',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'tokenAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ICOStatusChanged',
    inputs: [
      {
        name: 'brandId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'newStatus',
        type: 'uint8',
        indexed: false,
        internalType: 'enum ICOManager.ICOStatus',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      {
        name: 'version',
        type: 'uint8',
        indexed: false,
        internalType: 'uint8',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Paused',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TokensDistributed',
    inputs: [
      {
        name: 'brandId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'recipient',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Unpaused',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Upgraded',
    inputs: [
      {
        name: 'implementation',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'WhitelistCriteriaSet',
    inputs: [
      {
        name: 'brandId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'minTokenHold',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'minStake',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'minLPHold',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'AddressAlreadyWhitelisted',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'AddressNotWhitelisted',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'BatchLimitExceeded', inputs: [] },
  {
    type: 'error',
    name: 'ContributionTooHigh',
    inputs: [
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'maximum', type: 'uint256', internalType: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'ContributionTooLow',
    inputs: [
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'minimum', type: 'uint256', internalType: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'CriteriaNotMet',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'ICONotActive',
    inputs: [{ name: 'brandId', type: 'uint256', internalType: 'uint256' }],
  },
  {
    type: 'error',
    name: 'ICONotAvailable',
    inputs: [{ name: 'brandId', type: 'uint256', internalType: 'uint256' }],
  },
  { type: 'error', name: 'InsufficientBalance', inputs: [] },
  { type: 'error', name: 'InsufficientETHSent', inputs: [] },
  { type: 'error', name: 'InvalidAddress', inputs: [] },
  { type: 'error', name: 'InvalidAmount', inputs: [] },
  { type: 'error', name: 'InvalidCriteria', inputs: [] },
  { type: 'error', name: 'InvalidParameters', inputs: [] },
  { type: 'error', name: 'InvalidPath', inputs: [] },
  {
    type: 'error',
    name: 'InvalidStatus',
    inputs: [
      {
        name: 'current',
        type: 'uint8',
        internalType: 'enum ICOManager.ICOStatus',
      },
      {
        name: 'required',
        type: 'uint8',
        internalType: 'enum ICOManager.ICOStatus',
      },
    ],
  },
  { type: 'error', name: 'NothingToClaim', inputs: [] },
  { type: 'error', name: 'TokensAlreadyClaimed', inputs: [] },
  {
    type: 'error',
    name: 'Unauthorized',
    inputs: [{ name: 'caller', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'UnsupportedToken', inputs: [] },
]
