export default [
  { inputs: [], name: 'AdminCanNotBecomeSigner', type: 'error' },
  { inputs: [], name: 'AdminShareMustBeLessThanTotalAmount', type: 'error' },
  { inputs: [], name: 'AdminVaultCanNotBeSigner', type: 'error' },
  { inputs: [], name: 'AdminVaultCanNotBeZero', type: 'error' },
  { inputs: [], name: 'BuyerCanNotBeAdminVault', type: 'error' },
  { inputs: [], name: 'BuyerCanNotBeNonprofit', type: 'error' },
  { inputs: [], name: 'BuyerCanNotBeZero', type: 'error' },
  { inputs: [], name: 'CanNotScheduleDonationForPastDates', type: 'error' },
  { inputs: [], name: 'DonorCanNotBeZero', type: 'error' },
  { inputs: [], name: 'DonorsAndDonationRootsLengthMustBeSame', type: 'error' },
  { inputs: [], name: 'ETHTransferFailed', type: 'error' },
  { inputs: [], name: 'EmptyArray', type: 'error' },
  { inputs: [], name: 'IncorrectDurationForRecurringDonation', type: 'error' },
  { inputs: [], name: 'InsufficientETHSent', type: 'error' },
  { inputs: [], name: 'InvalidDonationProof', type: 'error' },
  { inputs: [], name: 'InvalidDonorAddress', type: 'error' },
  { inputs: [], name: 'InvalidNonproftiVault', type: 'error' },
  { inputs: [], name: 'InvalidPath', type: 'error' },
  { inputs: [], name: 'InvalidSignature', type: 'error' },
  { inputs: [], name: 'NonprofitCanNotBeZero', type: 'error' },
  { inputs: [], name: 'OnlyTrustedEntityAllowed', type: 'error' },
  { inputs: [], name: 'PaymentIdAlreadyProcessed', type: 'error' },
  { inputs: [], name: 'PreviousRecurringDonationNotDeposited', type: 'error' },
  { inputs: [], name: 'ProductQunatityCanNotBeZero', type: 'error' },
  { inputs: [], name: 'RecurringDonationAlreadyExecuted', type: 'error' },
  { inputs: [], name: 'RecurringDonationAlreadyExists', type: 'error' },
  { inputs: [], name: 'RecurringDonationCancelled', type: 'error' },
  { inputs: [], name: 'RecurringDonationDoesNotExist', type: 'error' },
  { inputs: [], name: 'RecurringDonationNotActiveYet', type: 'error' },
  { inputs: [], name: 'SellerCanNotBeZero', type: 'error' },
  { inputs: [], name: 'SettlementIdAlreadyProcesses', type: 'error' },
  { inputs: [], name: 'SettlementIdCanNotBeZer', type: 'error' },
  { inputs: [], name: 'SignatureExpired', type: 'error' },
  { inputs: [], name: 'SignerCanNotBeZero', type: 'error' },
  { inputs: [], name: 'SignerNotSet', type: 'error' },
  { inputs: [], name: 'TokenManagerCanNotBeZero', type: 'error' },
  { inputs: [], name: 'TokenNotWhitelistedOrBaseStableCoin', type: 'error' },
  { inputs: [], name: 'TradeHandlerCanNotBeAdmin', type: 'error' },
  { inputs: [], name: 'TradeHandlerCanNotBeAdminVault', type: 'error' },
  { inputs: [], name: 'TradeHandlerCanNotBeSigner', type: 'error' },
  { inputs: [], name: 'TradeHandlerCanNotBeTrustedEntity', type: 'error' },
  { inputs: [], name: 'TradeHandlerCanNotBeZero', type: 'error' },
  { inputs: [], name: 'TrustedEntityCanNotBeAdmin', type: 'error' },
  { inputs: [], name: 'TrustedEntityCanNotBeAdminVault', type: 'error' },
  { inputs: [], name: 'TrustedEntityCanNotBeSigner', type: 'error' },
  { inputs: [], name: 'TrustedEntityCanNotBeZero', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'previousAdmin', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newAdmin', type: 'address' },
    ],
    name: 'AdminChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'oldVault', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newVault', type: 'address' },
      { indexed: true, internalType: 'address', name: 'changedBy', type: 'address' },
    ],
    name: 'AdminVaultUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'beacon', type: 'address' }],
    name: 'BeaconUpgraded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'paymentId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'donor', type: 'address' },
      { indexed: true, internalType: 'address', name: 'nonprofitVault', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'token', type: 'address' },
      {
        indexed: false,
        internalType: 'enum IMVMNTManager.DonationType',
        name: 'donationType',
        type: 'uint8',
      },
    ],
    name: 'DonationReceived',
    type: 'event',
  },
  { anonymous: false, inputs: [], name: 'EIP712DomainChanged', type: 'event' },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' }],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nonprofit', type: 'address' },
      { indexed: false, internalType: 'address', name: 'nonprofitVault', type: 'address' },
    ],
    name: 'NonprofitAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
    name: 'Paused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'paymentId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'user', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'points', type: 'uint256' },
    ],
    name: 'PointsEarned',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'productId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'quantity', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'paymentId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'seller', type: 'address' },
      { indexed: false, internalType: 'address', name: 'buyer', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'adminShare', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'token', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'hasDonation', type: 'bool' },
    ],
    name: 'ProductSold',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nonprofitVault', type: 'address' },
      { indexed: false, internalType: 'address', name: 're2User', type: 'address' },
      { indexed: false, internalType: 'address', name: 'token', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'totalAmount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'adminShare', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'settlementId', type: 'uint256' },
    ],
    name: 'RE2DonationsSettled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'donor', type: 'address' },
      { indexed: false, internalType: 'bytes32', name: 'donationRoot', type: 'bytes32' },
    ],
    name: 'RecurringDonationActivated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'donor', type: 'address' },
      { indexed: false, internalType: 'bytes32', name: 'donationRoot', type: 'bytes32' },
    ],
    name: 'RecurringDonationDeactivated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'donor', type: 'address' },
      { indexed: false, internalType: 'bytes32', name: 'donationRoot', type: 'bytes32' },
    ],
    name: 'RecurringDonationDeactivatedByAdmin',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'oldSigner', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newSigner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'changedBy', type: 'address' },
    ],
    name: 'SignerUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'oldTokenManager', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newTokenManager', type: 'address' },
      { indexed: false, internalType: 'address', name: 'changedBy', type: 'address' },
    ],
    name: 'TokenManagerUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'oldHandler', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newHandler', type: 'address' },
      { indexed: true, internalType: 'address', name: 'changedBy', type: 'address' },
    ],
    name: 'TradeHandlerUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'oldTrustedEntity', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newTrustedEntity', type: 'address' },
      { indexed: true, internalType: 'address', name: 'changedBy', type: 'address' },
    ],
    name: 'TrustedEntityUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
    name: 'Unpaused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'Upgraded',
    type: 'event',
  },
  {
    inputs: [],
    name: 'MAXIMUM_DONATION_DURATION',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MINIMUM_DONATION_DURATION',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NATIVE_TOKEN',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'UINT256_MAX',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: '_adminVault',
    outputs: [{ internalType: 'address payable', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'adminVault',
    outputs: [{ internalType: 'address payable', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint256', name: 'productId', type: 'uint256' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'uint256', name: 'adminShare', type: 'uint256' },
          { internalType: 'uint256', name: 'buyerPoints', type: 'uint256' },
          { internalType: 'uint256', name: 'sellerPoints', type: 'uint256' },
          { internalType: 'uint256', name: 'paymentId', type: 'uint256' },
          { internalType: 'uint256', name: 'donationAmount', type: 'uint256' },
          { internalType: 'address', name: 'nonprofitVault', type: 'address' },
        ],
        internalType: 'struct IMVMNTManager.PaymentBatchInputParams[]',
        name: '_payments',
        type: 'tuple[]',
      },
      {
        components: [
          { internalType: 'address', name: 'buyer', type: 'address' },
          { internalType: 'address', name: 'seller', type: 'address' },
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'expiry', type: 'uint256' },
          { internalType: 'bytes', name: 'sign', type: 'bytes' },
        ],
        internalType: 'struct IMVMNTManager.CommonBatchInputParams',
        name: '_common',
        type: 'tuple',
      },
      { internalType: 'address[]', name: '_path', type: 'address[]' },
    ],
    name: 'batchPay',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '_donationRoot', type: 'bytes32' }],
    name: 'cancelRecurringDonation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: '_donors', type: 'address[]' },
      { internalType: 'bytes32[]', name: '_donationRoots', type: 'bytes32[]' },
    ],
    name: 'cancelRecurringDonations',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_nonprofitVault', type: 'address' },
      { internalType: 'address', name: '_token', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
      { internalType: 'uint256', name: '_points', type: 'uint256' },
      { internalType: 'uint256', name: '_paymentId', type: 'uint256' },
      { internalType: 'uint256', name: '_expiry', type: 'uint256' },
      { internalType: 'bytes', name: '_sign', type: 'bytes' },
      { internalType: 'address[]', name: '_path', type: 'address[]' },
    ],
    name: 'donate',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'donations',
    outputs: [
      { internalType: 'address', name: 'donor', type: 'address' },
      { internalType: 'address', name: 'nonprofitVault', type: 'address' },
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'enum IMVMNTManager.DonationType', name: 'donationType', type: 'uint8' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'eip712Domain',
    outputs: [
      { internalType: 'bytes1', name: 'fields', type: 'bytes1' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'version', type: 'string' },
      { internalType: 'uint256', name: 'chainId', type: 'uint256' },
      { internalType: 'address', name: 'verifyingContract', type: 'address' },
      { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
      { internalType: 'uint256[]', name: 'extensions', type: 'uint256[]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSignerAndAdminVault',
    outputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address payable', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTrustedEntityAndAdminVault',
    outputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address payable', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'signer_', type: 'address' },
      { internalType: 'address', name: '_trustedEntity', type: 'address' },
      { internalType: 'address payable', name: 'adminVault_', type: 'address' },
      { internalType: 'address', name: '_tokenManager', type: 'address' },
      { internalType: 'address', name: '_tradeHandler', type: 'address' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'isPaymentIdProcessed',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'isRe2SettlementIdProcessed',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'pause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint256', name: 'productId', type: 'uint256' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'uint256', name: 'adminShare', type: 'uint256' },
          { internalType: 'address', name: 'buyer', type: 'address' },
          { internalType: 'uint256', name: 'buyerPoints', type: 'uint256' },
          { internalType: 'address', name: 'seller', type: 'address' },
          { internalType: 'uint256', name: 'sellerPoints', type: 'uint256' },
          { internalType: 'uint256', name: 'paymentId', type: 'uint256' },
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'donationAmount', type: 'uint256' },
          { internalType: 'address', name: 'nonprofitVault', type: 'address' },
          { internalType: 'uint256', name: 'expiry', type: 'uint256' },
          { internalType: 'bytes', name: 'sign', type: 'bytes' },
        ],
        internalType: 'struct IMVMNTManager.PaymentInputParams',
        name: '_payment',
        type: 'tuple',
      },
      { internalType: 'address[]', name: '_path', type: 'address[]' },
    ],
    name: 'pay',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_nonprofitVault', type: 'address' },
      { internalType: 'address', name: '_token', type: 'address' },
      { internalType: 'uint256', name: '_totalAmount', type: 'uint256' },
      { internalType: 'uint256', name: '_adminShare', type: 'uint256' },
      { internalType: 'uint256', name: '_settlementId', type: 'uint256' },
      { internalType: 'uint256', name: '_expiry', type: 'uint256' },
      { internalType: 'bytes', name: '_sign', type: 'bytes' },
    ],
    name: 're2DonationSettlements',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'bytes32', name: '', type: 'bytes32' },
    ],
    name: 'recentRecurringDonationTime',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'donor', type: 'address' },
          { internalType: 'address', name: 'nonprofitVault', type: 'address' },
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint256', name: 'points', type: 'uint256' },
          { internalType: 'uint256', name: 'paymentId', type: 'uint256' },
          { internalType: 'uint256', name: 'expiry', type: 'uint256' },
          { internalType: 'bytes', name: 'sign', type: 'bytes' },
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'bytes32', name: 'donationRoot', type: 'bytes32' },
          { internalType: 'bytes32[]', name: 'donationProof', type: 'bytes32[]' },
          { internalType: 'uint256', name: 'executionScheduledAfter', type: 'uint256' },
        ],
        internalType: 'struct IMVMNTManager.RecurringDonationInput[]',
        name: '_donations',
        type: 'tuple[]',
      },
    ],
    name: 'recurringDonation',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: '_donationRoot', type: 'bytes32' },
      { internalType: 'uint256', name: '_firstExecutionScheduled', type: 'uint256' },
    ],
    name: 'registerRecurringDonation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address payable', name: 'adminVault_', type: 'address' }],
    name: 'setAdminVault',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'signer_', type: 'address' }],
    name: 'setSigner',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_tokenManager', type: 'address' }],
    name: 'setTokenManager',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_tradeHandler', type: 'address' }],
    name: 'setTradeHandler',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_trustedEntity', type: 'address' }],
    name: 'setTrustedEntity',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'signer',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'tokenManager',
    outputs: [{ internalType: 'contract ITokenManager', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'tradeHandler',
    outputs: [{ internalType: 'contract ITradeHandler', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'trustedEntity',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'unpause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [{ internalType: 'address', name: 'newImplementation', type: 'address' }],
    name: 'upgradeTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'newImplementation', type: 'address' },
      { internalType: 'bytes', name: 'data', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
]
