export default [
  { inputs: [], name: 'AdminCanNotBeMVMNTManager', type: 'error' },
  { inputs: [], name: 'AdminCanNotBeTrustedEntity', type: 'error' },
  { inputs: [], name: 'AdminCanNotBeWithdrawManager', type: 'error' },
  { inputs: [], name: 'BeaconOwnerCanNotBeZero', type: 'error' },
  { inputs: [], name: 'MVMNTManagerCanNotBeZero', type: 'error' },
  { inputs: [], name: 'NonprofitImpmenenationIsNotContract', type: 'error' },
  { inputs: [], name: 'OnlyTrustedEntityAllowed', type: 'error' },
  { inputs: [], name: 'ProjectIdAlreadyDeployed', type: 'error' },
  { inputs: [], name: 'ProjectIdCanNotBeZero', type: 'error' },
  { inputs: [], name: 'TrustedEntityCanNotBeZero', type: 'error' },
  { inputs: [], name: 'WithdrawManagerCanNotBeZero', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'previousAdmin', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newAdmin', type: 'address' },
    ],
    name: 'AdminChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'beacon', type: 'address' }],
    name: 'BeaconUpgraded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' }],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'oldMVMNTManager', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newMVMNTManager', type: 'address' },
      { indexed: false, internalType: 'address', name: 'changedBy', type: 'address' },
    ],
    name: 'MVMNTManagerUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'projectId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'nonprofitVault', type: 'address' },
      { indexed: false, internalType: 'address', name: 'nonprofit', type: 'address' },
    ],
    name: 'NonprofitVaultDeployed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'oldTrustedEntity', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newTrustedEntity', type: 'address' },
      { indexed: true, internalType: 'address', name: 'changedBy', type: 'address' },
    ],
    name: 'TrustedEntityUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'Upgraded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'oldWithdrawManager', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newWithdrawManager', type: 'address' },
      { indexed: false, internalType: 'address', name: 'changedBy', type: 'address' },
    ],
    name: 'WithdrawManagerUpdated',
    type: 'event',
  },
  {
    inputs: [],
    name: 'beacon',
    outputs: [{ internalType: 'contract UpgradeableBeacon', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_projectId', type: 'uint256' },
      { internalType: 'address', name: '_nonprofit', type: 'address' },
    ],
    name: 'createNonprofitVault',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getCurrentImplementation',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_mvmntManager', type: 'address' },
      { internalType: 'address', name: '_withdrawManager', type: 'address' },
      { internalType: 'address', name: '_trustedEntity', type: 'address' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'mvmntManager',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'nonprofitVaults',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_mvmntManager', type: 'address' }],
    name: 'setMVMNTManager',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_trustedEntity', type: 'address' }],
    name: 'setTrustedEntity',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_withdrawManager', type: 'address' }],
    name: 'setWithdrawManager',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newBeaconOwner', type: 'address' }],
    name: 'transferBeaconOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'trustedEntity',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newImplementation', type: 'address' }],
    name: 'upgradeNonprofitVaultImplementation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newImplementation', type: 'address' }],
    name: 'upgradeTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'newImplementation', type: 'address' },
      { internalType: 'bytes', name: 'data', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'withdrawManager',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
]
