export default [
  { inputs: [], name: 'IncorrectSenderForWithdrawId', type: 'error' },
  { inputs: [], name: 'InvalidSignature', type: 'error' },
  { inputs: [], name: 'MVMNTManagerCanNotBeZero', type: 'error' },
  { inputs: [], name: 'MVMNTManagerPaused', type: 'error' },
  { inputs: [], name: 'MismatchedArrayLengthNonprofitVaultTokenAndAmounts', type: 'error' },
  { inputs: [], name: 'OnlyTrustedEntityAllowed', type: 'error' },
  { inputs: [], name: 'ReceiverCanNotBeZero', type: 'error' },
  { inputs: [], name: 'SettlementsArrayLengthMismatchingNonprofitArrayLength', type: 'error' },
  { inputs: [], name: 'SignatureExpired', type: 'error' },
  { inputs: [], name: 'TokenManagerCanNotBeZero', type: 'error' },
  { inputs: [], name: 'TokenNotWithdrawable', type: 'error' },
  { inputs: [], name: 'WithdrawCompletedRevertedOrDoesNotExist', type: 'error' },
  { inputs: [], name: 'WithdrawIdAlreadyProcessed', type: 'error' },
  { inputs: [], name: 'WithdrawStillLocked', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'previousAdmin', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newAdmin', type: 'address' },
    ],
    name: 'AdminChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'beacon', type: 'address' }],
    name: 'BeaconUpgraded',
    type: 'event',
  },
  { anonymous: false, inputs: [], name: 'EIP712DomainChanged', type: 'event' },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' }],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'oldDuration', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'newDuration', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'updatedBy', type: 'address' },
    ],
    name: 'LockDurationUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'oldMVMNTManager', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newMVMNTManager', type: 'address' },
      { indexed: false, internalType: 'address', name: 'changedBy', type: 'address' },
    ],
    name: 'MVMNTManagerUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'oldTokenManager', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newTokenManager', type: 'address' },
      { indexed: false, internalType: 'address', name: 'changedBy', type: 'address' },
    ],
    name: 'TokenManagerUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'Upgraded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'user', type: 'address' },
      { indexed: false, internalType: 'address', name: 'token', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'withdrawId', type: 'uint256' },
    ],
    name: 'UserWithdrawCompleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'user', type: 'address' },
      { indexed: false, internalType: 'address', name: 'token', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'unlockTime', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'withdrawId', type: 'uint256' },
    ],
    name: 'UserWithdrawInitiated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'user', type: 'address' },
      { indexed: false, internalType: 'address', name: 'token', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'withdrawId', type: 'uint256' },
    ],
    name: 'UserWithdrawReverted',
    type: 'event',
  },
  {
    inputs: [],
    name: 'NATIVE_TOKEN',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'eip712Domain',
    outputs: [
      { internalType: 'bytes1', name: 'fields', type: 'bytes1' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'version', type: 'string' },
      { internalType: 'uint256', name: 'chainId', type: 'uint256' },
      { internalType: 'address', name: 'verifyingContract', type: 'address' },
      { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
      { internalType: 'uint256[]', name: 'extensions', type: 'uint256[]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_lockDuration', type: 'uint256' },
      { internalType: 'address', name: '_mvmntManager', type: 'address' },
      { internalType: 'address', name: '_tokenManager', type: 'address' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_withdrawId', type: 'uint256' },
      { internalType: 'address', name: '_token', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
      { internalType: 'uint256', name: '_expiry', type: 'uint256' },
      { internalType: 'bytes', name: '_sign', type: 'bytes' },
    ],
    name: 'initiateUserWithdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'lockDuration',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'mvmntManager',
    outputs: [{ internalType: 'contract IMVMNTManager', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: '_nonprofitVaults', type: 'address[]' },
      { internalType: 'address[]', name: '_tokens', type: 'address[]' },
      { internalType: 'uint256[]', name: '_amounts', type: 'uint256[]' },
      { internalType: 'address payable', name: '_receiver', type: 'address' },
    ],
    name: 'recoverNonVerifiedDonations',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_withdrawId', type: 'uint256' }],
    name: 'releaseFunds',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_withdrawId', type: 'uint256' }],
    name: 'revertUserWithdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256[]', name: '_withdrawIds', type: 'uint256[]' }],
    name: 'revertUserWithdrawBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_lockDuration', type: 'uint256' }],
    name: 'setLockDuration',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_tokenManager', type: 'address' }],
    name: 'setTokenManager',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'adminShare', type: 'uint256' },
          { internalType: 'uint256', name: 'nonprofitWithdrawableFunds', type: 'uint256' },
        ],
        internalType: 'struct INonprofitVault.Settlement[]',
        name: '_settlements',
        type: 'tuple[]',
      },
      { internalType: 'address', name: '_nonprofitVault', type: 'address' },
    ],
    name: 'settleDonation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'adminShare', type: 'uint256' },
          { internalType: 'uint256', name: 'nonprofitWithdrawableFunds', type: 'uint256' },
        ],
        internalType: 'struct INonprofitVault.Settlement[][]',
        name: '_settlements',
        type: 'tuple[][]',
      },
      { internalType: 'address[]', name: '_nonprofitVaults', type: 'address[]' },
    ],
    name: 'settleDonationBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'tokenManager',
    outputs: [{ internalType: 'contract ITokenManager', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newImplementation', type: 'address' }],
    name: 'upgradeTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'newImplementation', type: 'address' },
      { internalType: 'bytes', name: 'data', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: '_tokens', type: 'address[]' },
      { internalType: 'address[]', name: '_nonprofitVaults', type: 'address[]' },
    ],
    name: 'withdrawMaxBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'withdrawals',
    outputs: [
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'uint256', name: 'unlockTime', type: 'uint256' },
      { internalType: 'enum IWithdrawManager.WithdrawalStatus', name: 'status', type: 'uint8' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
]
