import { Conditions, Fields } from '@app/src/admin/homepages/enums'

export const DealConditionRules = {
  [Fields.DEAL_NAME]: [Conditions.CONTAINS, Conditions.DOES_NOT_CONTAIN],
  [Fields.DEAL_BRAND]: [Conditions.IS_EQUAL_TO],
  [Fields.DEAL_CATEGORY]: [Conditions.IS_EQUAL_TO],
  [Fields.DEAL_TYPE]: [Conditions.IS_EQUAL_TO, Conditions.IS_NOT_EQUAL_TO],
  [Fields.DEAL_PRICE]: [Conditions.IS_GREATER_THAN, Conditions.IS_LESS_THAN],
  [Fields.DEAL_CURRENCY]: [Conditions.IS_EQUAL_TO],
  [Fields.DEAL_STATUS]: [Conditions.IS_EQUAL_TO, Conditions.IS_NOT_EQUAL_TO],
  [Fields.DONATED_TO]: [Conditions.CONTAINS, Conditions.DOES_NOT_CONTAIN],
  [Fields.TOTAL_LIKES]: [Conditions.IS_GREATER_THAN, Conditions.IS_LESS_THAN],
  [Fields.USER_TYPE]: [Conditions.IS_EQUAL_TO, Conditions.IS_NOT_EQUAL_TO],
  [Fields.DONATION_AMOUNT]: [Conditions.IS_GREATER_THAN, Conditions.IS_LESS_THAN],
  [Fields.TOTAL_SALES]: [Conditions.IS_GREATER_THAN, Conditions.IS_LESS_THAN],
  [Fields.USER_MVMNT_FOLLOWERS]: [Conditions.IS_GREATER_THAN, Conditions.IS_LESS_THAN],
  [Fields.USER_SNS_FOLLOWERS]: [Conditions.IS_GREATER_THAN, Conditions.IS_LESS_THAN],
  [Fields.SORT_ORDER]: [
    Conditions.DEAL_START_DATE_ASC,
    Conditions.DEAL_START_DATE_ASC,
    Conditions.DEAL_END_DATE_DESC,
    Conditions.DEAL_END_DATE_ASC,
    Conditions.LIKE_COUNT_ASC,
    Conditions.LIKE_COUNT_DESC,
    Conditions.DEAL_PRICE_DESC,
    Conditions.DEAL_PRICE_ASC,
    Conditions.DONATION_AMOUNT_ASC,
    Conditions.DONATION_AMOUNT_DESC,
    Conditions.TOTAL_SALES_ASC,
    Conditions.TOTAL_SALES_DESC,
    Conditions.MVMNT_FOLLOWERS_ASC,
    Conditions.MVMNT_FOLLOWERS_DESC,
    Conditions.SNS_FOLLOWERS_ASC,
    Conditions.SNS_FOLLOWERS_DESC,
  ],
}
