export enum IntegrationDonationType {
  FIXED_PER_ORDER = 'FIXED_PER_ORDER',
  PERCENTAGE_TOTAL_ORDER = 'PERCENTAGE_TOTAL_ORDER',
  ROUND_UP_TOTAL_PRICE = 'ROUND_UP_TOTAL_PRICE',
  FIXED_AMOUNT_PER_PRODUCT = 'FIXED_AMOUNT_PER_PRODUCT',
  PERCENTAGE_OF_PRODUCT = 'PERCENTAGE_OF_PRODUCT',
  ROUND_UP_PER_PRODUCT = 'ROUND_UP_PER_PRODUCT',
}
