export enum BusinessType {
  CORPORATION = 'CORPORATION',
  SOLE_PROPRIETOR = 'SOLE_PROPRIETOR',
  INDIVIDUAL_PERSONAL = 'INDIVIDUAL_PERSONAL',
  INDIVIDUAL_INFLUENCER = 'INDIVIDUAL_INFLUENCER',
}
