import { UserTypes } from '@app/shared/enums'

export enum UserAccountType {
  BUSINESS_COMPANY = UserTypes.BUSINESS_COMPANY,
  INDIVIDUAL_PERSONAL = UserTypes.INDIVIDUAL_PERSONAL,
  RE2_SHOPIFY_TEMP_USER = UserTypes.RE2_SHOPIFY_TEMP_USER,
  INDIVIDUAL_INFLUENCER = UserTypes.INDIVIDUAL_INFLUENCER,
  BUSINESS_SOLE_PROPRIETOR = UserTypes.BUSINESS_SOLE_PROPRIETOR,
}
