export enum Fields {
  DEAL_NAME = 'DEAL_NAME',
  DEAL_BRAND = 'DEAL_BRAND',
  DEAL_CATEGORY = 'DEAL_CATEGORY',
  DEAL_TYPE = 'DEAL_TYPE',
  USER_TYPE = 'USER_TYPE',
  DONATED_TO = 'DONATED_TO',
  DONATION_AMOUNT = 'DONATION_AMOUNT',
  TOTAL_SALES = 'TOTAL_SALES',
  USER_SNS_FOLLOWERS = 'USER_SNS_FOLLOWERS',
  USER_MVMNT_FOLLOWERS = 'USER_MVMNT_FOLLOWERS',
  SORT_ORDER = 'SORT_ORDER',
}
