import { ContributionStarType } from '@app/src/users/stars/enums'

export const CONTRIBUTION_STAR_AMOUNT: Record<ContributionStarType, number> = {
  SHARE_DEAL: 10,
  INVITED_SALE: 15,
  RE2_DONATION: 50,
  RESALE_ORDER: 50,
  FRIEND_INVITE: 20,
  ORDER_CREATED: 50,
  DIRECT_DONATION: 50,
  INVITED_PURCHASE: 15,
  SHARE_NONPROFIT: 10,
  SHARE_FUNDRAISER: 10,
  INVITED_RE2_DONATION: 15,
  SHARE_DONATION_PROJECT: 10,
  INVITED_DIRECT_DONATION: 15,
}
