import { Status } from '@app/src/shared/enums'

export enum CartStatus {
  PAID = Status.PAID,
  SHIPPED = Status.SHIPPED,
  PENDING = Status.PENDING,
  COMPLETED = Status.COMPLETED,
  CANCELLED = Status.CANCELLED,
  PROCESSED = Status.PROCESSED,
  REVIEW_DEAL = Status.REVIEW_DEAL,
  WAITING_SHIPMENT = Status.WAITING_SHIPMENT,
  PARTIALLY_SHIPPED = Status.PARTIALLY_SHIPPED,
  PARTIALLY_CANCELLED = Status.PARTIALLY_CANCELLED,
}
