import { Query } from '@app/src/shared/enums'

export enum IncludesQuery {
  DEAL = Query.DEAL,
  DEAL_IMAGES = Query.DEAL_IMAGES,
  DEAL_USER = Query.DEAL_USER,
  DEAL_USER_PROFILE = Query.USER_PROFILE,
  PROFILE_IMAGE = Query.PROFILE_IMAGES,
  VARIANT = Query.VARIANT,
  VARIANT_OPTIONS = Query.VARIANT_OPTIONS,
  VARIANT_OPTIONS_OPTION = Query.VARIANT_OPTIONS_OPTION,
  VARIANT_OPTIONS_OPTION_VALUE = Query.VARIANT_OPTIONS_OPTION_VALUE,
}
