export enum NotificationSettingType {
  DEAL_LIKE = 'DEAL_LIKE',
  NEW_COUPON = 'NEW_COUPON',
  BID_ON_AUCTION = 'BID_ON_AUCTION',
  FOLLOWING_NEW_DEAL = 'FOLLOWING_NEW_DEAL',
  PURCHASE_ON_RAFFLE = 'PURCHASE_ON_RAFFLE',
  NEW_ACTIVITY_REPORT_NONPROFIT = 'NEW_ACTIVITY_REPORT_NONPROFIT',
  NEW_DONATION_PROJECT_NONPROFIT = 'NEW_DONATION_PROJECT_NONPROFIT',
}
