export enum UserTypes {
  RE2 = 'RE2',
  ADMIN = 'ADMIN',
  NONPROFIT = 'NONPROFIT',
  BUSINESS_COMPANY = 'BUSINESS_COMPANY',
  INDIVIDUAL_PERSONAL = 'INDIVIDUAL_PERSONAL',
  RE2_SHOPIFY_TEMP_USER = 'RE2_SHOPIFY_TEMP_USER',
  INDIVIDUAL_INFLUENCER = 'INDIVIDUAL_INFLUENCER',
  BUSINESS_SOLE_PROPRIETOR = 'BUSINESS_SOLE_PROPRIETOR',
}
