import { Query } from '@app/src/shared/enums'

export enum IncludesQuery {
  IMAGES = Query.IMAGES,
  VARIANTS = Query.VARIANTS,
  VARIANTS_IMAGES = Query.VARIANTS_IMAGES,
  OPTIONS = Query.OPTIONS,
  OPTION_VALUES = Query.OPTION_VALUES,
  OPTION_VALUES_OPTION = Query.OPTION_VALUES_OPTION,
  RAFFLES = Query.RAFFLES,
  RAFFLE_PRIZES = Query.RAFFLE_PRIZES,
  RAFFLE_PRIZES_IMAGES = Query.RAFFLE_PRIZES_IMAGES,
  BRAND = Query.BRAND,
  CATEGORY = Query.CATEGORY,
}
