export enum CancellationReason {
  ORDER_CREATED_BY_MISTAKE = 'ORDER_CREATED_BY_MISTAKE',
  ITEM_WOULD_NOT_ARRIVE_ON_TIME = 'ITEM_WOULD_NOT_ARRIVE_ON_TIME',
  SHIPPING_COST_TOO_HIGH = 'SHIPPING_COST_TOO_HIGH',
  ITEM_PRICE_TOO_HIGH = 'ITEM_PRICE_TOO_HIGH',
  FOUND_CHEAPER_SOMEWHERE_ELSE = 'FOUND_CHEAPER_SOMEWHERE_ELSE',
  NEED_TO_CHANGE_SHIPPING_ADDRESS = 'NEED_TO_CHANGE_SHIPPING_ADDRESS',
  NEED_TO_CHANGE_SHIPPING_SPEED = 'NEED_TO_CHANGE_SHIPPING_SPEED',
  NEED_TO_CHANGE_BILLING_ADDRESS = 'NEED_TO_CHANGE_BILLING_ADDRESS',
  NEED_TO_CHANGE_PAYMENT_METHOD = 'NEED_TO_CHANGE_PAYMENT_METHOD',
  OTHER = 'OTHER',
}
