export enum CancellationLogAction {
  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
}
