import { Query } from '@app/src/shared/enums'

export enum IncludesQuery {
  IMAGES = Query.IMAGES,
  VARIANTS = Query.VARIANTS,
  OPTION_VALUES = Query.OPTION_VALUES,
  OPTIONS = Query.OPTIONS,
  RAFFLES = Query.RAFFLES,
  RAFFLE_PRIZES = Query.RAFFLE_PRIZES,
  RAFFLE_PRIZES_IMAGES = Query.RAFFLE_PRIZES_IMAGES,
  USER = Query.USER,
  CATEGORY = Query.CATEGORY,
  BRAND = Query.BRAND,
  SHIPPING_METHOD = Query.SHIPPING_METHOD,
  DONATION_NONPROFIT = Query.DONATION_NONPROFIT,
  DONATION_NONPROFIT_PROFILE = Query.DONATION_NONPROFIT_PROFILE,
  DONATION_PROJECT = Query.DONATION_PROJECT,
  USER_PROFILE = Query.USER_PROFILE,
}
