export enum USER_WITHDRAWAL_STATUS {
  INITIATED = 'INITIATED',
  LOCKED = 'LOCKED',
  REVERTED = 'REVERTED',
  UNLOCKED = 'UNLOCKED',
  REJECTED = 'REJECTED',
  WITHDRAWING = 'WITHDRAWING',
  COMPLETED = 'COMPLETED',
}
