name: Build and Deploy Backend

on:
  push:
    branches:
      - develop

env:
  IMAGE_NAME: mvmnt/backend:latest
  AUTH_PRIVATE_KEY: ${{ secrets.AUTH_PRIVATE_KEY }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME \
            --build-arg AUTH_PRIVATE_KEY="$AUTH_PRIVATE_KEY"

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DEV_DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Push image to digitalocean
        run: |
          doctl registry login --expiry-seconds 240
          docker tag $IMAGE_NAME registry.digitalocean.com/mvmnts/$IMAGE_NAME
          docker push registry.digitalocean.com/mvmnts/$IMAGE_NAME

      - uses: appleboy/ssh-action@master
        name: Deploy to server
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            set -e
            docker image prune --force --all --filter "until=24h"
            cd /var/www/mvmnt-backend
            git reset --hard HEAD^1
            git checkout develop
            git pull origin develop
            docker-compose -f docker-compose.dev.yaml pull
            docker-compose -f docker-compose.dev.yaml down
            docker-compose -f docker-compose.dev.yaml up -d
            set +e

      - name: Remove old images from Container Registry
        uses: henrik242/docr-image-remove@v1
        with:
          image_repository: mvmnt/backend
          buffer_size: 10
          exclude: ^(latest)$
